### ISSUE TITLE
Audience segment definition

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1002]
Make use of conscious chooser research

**Comment by tlasadea** [comment]
@hannahkane @caltrider the above mentioned research is here: https://drive.google.com/file/d/0B2wvfBjG7Mb1S1VKblFBVUlzRk0/view

**Comment by tlasadea** [comment]
Hey @beccaklam here: https://docs.google.com/a/mozilla.com/presentation/d/1wh1j6GC2Eyv6aaT8SSq87cqBe_xujNPF5obXCebllU4/edit?usp=sharing

First 3 slides are really what you may find useful at this point; the rest are because found some other good research that I'll also add because it may be useful for messaging etc.

**Comment by tlasadea** [comment]
It's here! https://docs.google.com/presentation/d/12WbLBZmOAtgDWBCdP7E6mspszYKHRPJaZf72Daqhh3g/edit#slide=id.g1fb36e97f3_0_176
