### ISSUE TITLE
Build next iteration of copyright site

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1020]
Per [mockups](https://redpen.io/p/tjd37e069720f9308a)

QA for the build will include:
- [ ] Design matches mockup, OK'ed by @natalieworth 
- [x] Works on various devices
- [x] Nav items updated
- [x] All links/buttons work
- [x] Call tool workflow as expected, inc:
  - [x] Country code defaults to browser locale, but user can overwrite
  - [x] Error message on phone number field
  - [x] User is matched with an MEP that speaks their language (based on site language, which is based on browser settings or user override)
  - [x] User sees "Calling your phone now" message during call
  - [x] User hears pre-recorded intro message
  - [x] "Try calling again" flow works (left a question in the redpen about the expected behavior)
  - [x] Share flow works
- [x] Remove languages from pulldown, except for English, French, Spanish, Italian, German and Polish
- [x] Newsletter sign-up functional, inc. error messages
- [x] Sticky CTA footer
- [x] Localisation check per locale (i.e. all of the above, per locale), OK'ed by @TheoChevalier 
- [x] EN copy OK'ed by @Melechuga

**Comment by hannahkane** [comment]
@Melechuga @ScottDowne @natalieworth @TheoChevalier - can you please review the checklist above? Feel free to add items.

**Comment by TheoChevalier** [comment]
Looks good on the l10n side, just added Polish as it’s a requested locale

**Comment by hannahkane** [comment]
@Melechuga - what would you consider NOT essential to launch? These are the things that I think we could launch without:
- [ ] Design matches mockup - we don't necessarily need it to be pixel perfect
- [ ] User hears pre-recorded intro message - could skip this if we aren't able to get the audio files in time
- [ ] "Try calling again" flow works - could just remove this if the flow is complicated
- [ ] Share flow works - this would be a huge bummer, but technically we could launch without a Share step
- [ ] Newsletter sign-up functional - I doubt this would be a big win in terms of time saved, but doesn't feel essential
- [ ] Sticky CTA footer - could certainly live without this

What do you think?

**Comment by Melechuga** [comment]
Thanks for pulling this together, @hannahkane!
I was thinking about it all, and if it's only a few days' delay in launching due to QA, I doubt it'll be a huge issue. I've slated the email to go out on Sept. 7th; do you think the site could be ready by then? If not, here are my notes on features we could launch without:

- About "try calling again" - I'm ok with nixing that if, simply by refreshing, the user gets back to the same page. 
- True that the recording isn't vital to being connected, however I think this is more on the CallPower side than on our side...?
- Not having "share" or the newsletter sign up would be sad, but I think nixing the "newsletter sign up" wouldn't be the end of the world.
- If we're getting rid of the sticky CTA footer, I would want to put a "Call Now" button at each paragraph break on the "Impact" page to break up the text, and give people the opportunity to call after they read how it would impact them as a technologist/creator/scientist.

**Comment by hannahkane** [comment]
Thanks, @Melechuga. Perhaps we can get an updated estimate from @Pomax and @ScottDowne on Monday.

(The audio recording is on our side in that we have to make the recordings, but it sounds like that's [moving along](https://github.com/MozillaFoundation/Advocacy/issues/1021#issuecomment-324734101).)

**Comment by hannahkane** [comment]
@Melechuga @TheoChevalier @natalieworth - do you have time to help QA the [staging site](https://changecopyright-org-staging.herokuapp.com), per the items in the first comment above?

**Comment by Melechuga** [comment]
@hannahkane yes! I can def help. What's the staging site url? Where should comments/bugs be filed?

**Comment by hannahkane** [comment]
https://changecopyright-org-staging.herokuapp.com/en-US/

Please file bugs in this repo.

**Comment by Melechuga** [comment]
QA, page 1 (links)
- "We’ll provide you with what to say before calling." link goes nowhere; should link to the "call now" page. 
- "technologist" "creator/innovator" and "scientist/librarian" sections don't link to the respective sections on the "Impact" page; each category should link.
- Also, "(Learn More)" links at the end of each paragraph are unlinked (and should be underlined when hyperlinked).

**Comment by Melechuga** [comment]
QA, EN Fix Copyright page (newsletter sign-up):
- "Join our newsletter" section: 
   - accepts an incomplete email address
   - upon clicking "subscribe", it takes you to http://share.mozilla.org/352/179362 which is just one massive image  -- this should probably link to an existing "thank you" site that has to do with the newsletter sign-up, maybe like https://www.mozilla.org/en-US/newsletter/mozilla/
   - Design is off kilter:
![screen shot 2017-08-29 at 4 44 39 pm](https://user-images.githubusercontent.com/5815317/29849085-6a624d00-8cd9-11e7-89c9-882906cdab53.png)

**Comment by Melechuga** [comment]
QA, EN Fix Copyright page, copy:
Creator/Innovator section, the copy is "all the forms of expression that makes the internet wonderful." One grammar change -- "makes" should be "**make**"

**Comment by TheoChevalier** [comment]
> QA, Fix Copyright page, copy:
Creator/Innovator section, the copy is "all the forms of expression that makes the internet wonderful." One grammar change -- "makes" should be "make"

Thanks, fixed it

**Comment by Melechuga** [comment]
QA, Impact page, links:
- Assuming the top design (super cute!) is just a placeholder (screenshot below), but each one should link to the respective section on the page below.
![screen shot 2017-08-29 at 4 52 30 pm](https://user-images.githubusercontent.com/5815317/29849674-305c1e7a-8cdd-11e7-9435-e687e854a91d.png)
- None of the "For more detail..." links go to the appropriate site.

**Comment by Melechuga** [comment]
QA, Impact page, copy:
- In one of the design mockups, there was a comment about making the questions "What does this mean?" and "What are we fighting for?" bold or in someway more visibly catchy; is this still the case? At the very least, if we could bold them that would be helpful.
- Under the Creator/Innovator section, the "For more detail..." link says "For more details..." -- should not have the s.

**Comment by Melechuga** [comment]
QA, Call Now page:
"Enter Phone Number" example text doesn't fit in box (number box isn't dependent on window width":
![screen shot 2017-08-29 at 5 17 32 pm](https://user-images.githubusercontent.com/5815317/29849821-2df92046-8cde-11e7-851a-7f4de0019f30.png)

**Comment by Melechuga** [comment]
QA, ES Reforma de... page, links:
- "Antes de llamar te indicaremos qué puedes decir." (below the "Llamar Ahora" button) isn't linked; should go to the "Llamar Ahora" page.
- Same as on the EN pages, none of the links for the various personas go to the "Impacto" page to their respective section -- **I'm assuming this is now the same for all localized pages as well**. 
- Footer: the "Legal" and "Privacidad" links go the EN pages; should link to:
Legal: https://www.mozilla.org/es-ES/about/legal/terms/mozilla/
Privacided: https://www.mozilla.org/es-ES/privacy/websites/
**I'm assuming all the localized pages link to these as well; can we make sure they link to the respective ones for their languages?** 
- Footer: "Donar" also goes to the EN page; not sure if there is a localized version. @TheoChevalier

**Comment by Melechuga** [comment]
QA, ES Reforma de... page, newsletter sign-up:
Screenshot shows the example in the email field ("Dirección de correo electrónico) doesn't fit in the box:
![screen shot 2017-08-29 at 5 28 29 pm](https://user-images.githubusercontent.com/5815317/29850053-a2b8228c-8cdf-11e7-8882-7afebc323e73.png)

Also, it accepts an incomplete email address.
The thank you/share page, though, is fantastic!
![screen shot 2017-08-29 at 5 30 25 pm](https://user-images.githubusercontent.com/5815317/29850078-ca98bab4-8cdf-11e7-86e1-5747503a7b6f.png)

**Comment by Melechuga** [comment]
QA, ES Impacto page, copy (localization issues):
- Same design issue as EN page -- the "¿Eso qué significa?" and "¿Por qué estamos luchando?" on all section could be in bold or otherwise more visible.
- 3 out of the 4 "For more detail, read C4C’s facstheet (PDF, in English)." are in English. @TheoChevalier can you please add in the ES versions?
- Sections "Creador/innovador" and "Cientifico/bibliotecario" are still in EN; need ES versions.

**Comment by Melechuga** [comment]
QA, ES site links:
When on the landing page in ES ("Reforma de..."), clicking on either "Impacto" or "Llamar Ahora" at the top takes user to the EN page, instead of to the ES versions. Same when moving between pages -- everything takes you to the EN pages. Not sure if this is because of my IP, but this shouldn't be the case if someone has chosen their localized site.

**Comment by TheoChevalier** [comment]
> Footer: the "Legal" and "Privacidad" links go the EN pages; should link to:
Legal: https://www.mozilla.org/es-ES/about/legal/terms/mozilla/
Privacided: https://www.mozilla.org/es-ES/privacy/websites/
> I'm assuming all the localized pages link to these as well; can we make sure they link to the respective ones for their languages?
Footer: "Donar" also goes to the EN page; not sure if there is a localized version.

Those are okay, people will be properly redirected to the appropriate language. You’re being redirected to English because en-US is set as your preferred language in Preferences > Content > Language.

> Under the Creator/Innovator section, the "For more detail..." link says "For more details..." -- should not have the s.

Fixed, thanks

> 3 out of the 4 "For more detail, read C4C’s facstheet (PDF, in English)." are in English. @TheoChevalier can you please add in the ES versions?
Sections "Creador/innovador" and "Cientifico/bibliotecario" are still in EN; need ES versions.

Yup, it’s coming https://pontoon.mozilla.org/es/copyright-campaign/

> QA, ES site links:
When on the landing page in ES ("Reforma de..."), clicking on either "Impacto" or "Llamar Ahora" at the top takes user to the EN page, instead of to the ES versions. Same when moving between pages -- everything takes you to the EN pages. Not sure if this is because of my IP, but this shouldn't be the case if someone has chosen their localized site.

Dupe of https://github.com/MozillaFoundation/Advocacy/issues/1047

**Comment by hannahkane** [comment]
Thanks for the awesome QA, @Melechuga. I deleted a couple of your comments only because they'd been filed separately.

**Comment by ScottDowne** [comment]
A bunch of these got fixed.

I see the largest issues left, after reading through this, to be:

- [x] SIgnup in english doesn't have a correct thank you page, still using the share progress page we had for the previous campaign.
- [x] Singnup input placeholder gets cut off in some languages.
- [x] Sticky buttons.

Let me know if I missed anything and we can walk through it.

**Comment by natalieworth** [comment]
Sorry @ScottDowne I'm not seeing sticky button updates? Or is it coming? These aren't sticky for me yet:
<img width="1434" alt="screen shot 2017-08-30 at 2 20 00 pm" src="https://user-images.githubusercontent.com/14876567/29895623-ac4f07de-8d8e-11e7-9b09-421a54d98c0a.png">
<img width="1434" alt="screen shot 2017-08-30 at 2 20 07 pm" src="https://user-images.githubusercontent.com/14876567/29895622-ac3b81fa-8d8e-11e7-949c-a16619cef0b1.png">

**Comment by ScottDowne** [comment]
I only put sticky on impact.

**Comment by hannahkane** [comment]
I've updated the checklist in the first comment of this ticket. @natalieworth @TheoChevalier and @Melechuga - if you feel the design, localization, and copy—respectively—are good for launch (we can continue to make small changes afterwards), please check the corresponding boxes in the checklist.

I don't know how to test the two remaining pieces in the call tool—checking to see that the user gets matched with the right MEP, and hears the right audio file. @Pomax - do you know how I can test that? Or are we not able to test until we push this live?

**Comment by TheoChevalier** [comment]
Also what I can’t test:
- Share buttons are properly displayed after the call
- if `(+33) 0611223344` is accepted as well as `(+33) 611223344`

Otherwise, everything looks good to me on the localization side

**Comment by Melechuga** [comment]
Copy ok'd by me! The newsletter text is still a bit wonky tho (if that's by design, ignore me!):
![screen shot 2017-08-29 at 4 44 39 pm](https://user-images.githubusercontent.com/5815317/29932008-e13f032e-8e27-11e7-87cc-d688e7fab770.png)

**Comment by ScottDowne** [comment]
Wonky signup css should be fixed in a bit.

**Comment by hannahkane** [comment]
Closing this ticket. Any additional changes should be filed as separate tickets.
