### ISSUE TITLE
Copyright: soft reload does not reset country code

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#1048]
On https://changecopyright-org-staging.herokuapp.com/fr/call-now:

1- switching to +44 (UK)
2 - refreshing the page

Get this state where +33 is set, but +44 is the one selected:

<img width="102" alt="capture d ecran 2017-08-30 a 16 32 03" src="https://user-images.githubusercontent.com/1294206/29880857-cf33f3ba-8da0-11e7-800b-308bb6567aae.png">

**Comment by ScottDowne** [comment]
I'm working on this, a bug somewhere.

I have a nonsense workaround that I shouldn't have to do.

**Comment by ScottDowne** [comment]
OK, after a bit of investigation, I have an understanding of the bug and an adequate fix.

https://github.com/mozilla/copyright/pull/112

Should be building now, so we can close this.

The explanation of this is as follows.

The browser auto fills inputs based on previous values stored in cache.

React also diffs the page to see if it needs to update or not.

In the case of no server side rendering, the html is empty on page load, then react diffs an empty page to contain all the markup, in the case of server side rendering, react decides nothing has changed, and does nothing. However, the browser has at some point changed something that react seems to ignore.

I figure the fix is to actually get react to update it's state based on the values in the browser, keeping the intended browser functionality.
