### ISSUE TITLE
QA the site as it currently is

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#1088]
I'm mostly just looking for people to find things I have missed.

I'll be doing my own rotation of QA, but any help is appreciated.

Staging is here: https://advocacy-mozilla-org-st-pr-395.herokuapp.com/en-US/privacynotincluded

Comps are here: https://redpen.io/p/jbf0c36c8838f136ad

The product page isn't complete. Neither are images and copy, but still feel free to take a look at it.

Comment in this ticket with any issues you find however you see fit.

@natalieworth @beccaklam

**Comment by hannahkane** [comment]
Email modal shouldn't appear more than once in a session

**Comment by ScottDowne** [comment]
Right, I think we talked about a hard refresh makes it appear again?

**Comment by hannahkane** [comment]
I think that's probably fine, yeah.

**Comment by hannahkane** [comment]
Email field on modal doesn't validate email address format.

**Comment by hannahkane** [comment]
Should "m" in nav bar go somewhere? cc @beccaklam @natalieworth?

**Comment by hannahkane** [comment]
Legal links seem good to me. We might want to add a cc license. @caltrider - in your discussions with Legal, did they review the footer?

**Comment by hannahkane** [comment]
- [x] Not sure if possible to fix, but there's a bunch of extra whitespace between the Coral section and the Related Items section

**Comment by ScottDowne** [comment]
@hannahkane Fixed the signup box showing up too often.

**Comment by beccaklam** [comment]
@ScottDowne Should I be QA-ing CSS right now?

**Comment by beccaklam** [comment]
@ScottDowne 

@ScottDowne 
Landing Page - Desktop

- [x] h1 should be Playfair Display Black, not Regular
- [x] point size is 70px (didn't see your rems so not sure what you're using as your base)
- [x] p under h1 should be Playfair Display Bold, point size 37px
- [x] drop cap should be Playfair Display Black
- [ ] line-height bump up to 1.5rem
- [x] 'HE HOLIDAYS' should be Playfair Display Bold, with letter spacing is 1.5
- [ ] the arrow pointing down should be slimmer (I can export one for you)
- [x] all italicized fonts need to be Playfair Display Italic
- [x] See The Guide is Playfair Display Black, point size 52px
- [x] Swipe or scroll should be Playfair Display Italic, point size 22px

More to come ... would it be easier if I made these changes?

**Comment by HPaulJohnson** [comment]
Some feedback from my initial pass at QA: 
**Home Page**
- [x] The *Privacy Not Included Headline feels really undersized to me, which is contributing to a pretty underwhelming first impression when I land on this page. I'm anxious about high bounce rates with all of the content being below the fold. At the very least we need some sort of CTA visible on landing (eg. "browse products". 
- [x] In a similar way, I worry the down arrow isn't clear enough that one needs to scroll to get to content. People may want to click. Also a bit awkward that if I do make it to the first piece of content, only then does it say swipe or scroll to begin.
- [x] In general the scrolling is sticky and inconsistent. Sometime it takes multiple swipes to get the page to move. This is happening on a desktop across browsers.
- [x] When you get to any given category on the homepage, it's not immediately obvious what to do next. i.e. "Toys" doesn't look clickable and there is not CTA like "browse toys"

**Why We Made This Guide Page**
- [x] Another weird landing experience when I click on this from the categories dropdown: All I see above the fold is "Why We Made This" and a button to "See the Guide" that takes me back to the homepage (when presumably, I was coming to this page from the guide for more info). I think we need to update the headline to make it more interesting and/or add a subhead and remove the "See the Guide" button. 
- [x] This page in particular feels like a place where we need to bring the content/copy way up on the page. It's lost as is. 

**Email Modal**
- [x] Email modal pops too fast on product detail pages. I believe @tlasadea has suggested it be triggered based on some scrolling activity on the page instead.

~~- Email modal checkbox disclaimer still has placeholder text displaying "I’m okay with mozilla handling my info as explained in {linkPrivacyNotice}"~~
**Edit by Théo**: this got broken when I edited the strings, I have a fix in a pending pull request

**Product Reviews**
- [x] Where will the link go in the final version (will the photo be hyperlinked, will the product name be hyperlinked, etc) - I'm assuming it's not just a red, long link that we will be displaying. 
- [x] The "copy link" button on the product descriptions is problematic. This is not intended to be a primary CTA (we'd rather have people share the site) yet the red button makes it the most prominent thing on the page. I'd suggest we do it as a text link underneath the product photo/blurb, or at the bottom of the description. 
- [x] Categories breadcrumb takes me back to homepage, not categories.
- [x] In the "Can It Spy On Me" presentation is confusing. Take the Wink Hub product for example. Camera and microphone are blank and without any context I have no idea to read this; does the fact they are included in the list at all mean something? The "tracks location" has a red check, so I'm assuming it does this. I think we need some form of graphic symbol on all the various data points, so "camera/mic" should have an X or some other way of communicating that it doesn't use these things. 
- [x] I find the second section -  "what does it know about me" - hard to read. the other two sections have alternating gray/white background for the datapoints while this one doesn't. Why is this section styled different than the other two? 
- [x] For the 3rd section - "3rd party data" - it's just populated with "???" for all products and I'm going to assume that's just placeholder as we wait for content. 
- [x] The red link styling draws a lot of attention to those parts of content. I don't think those are primary CTA's at all so I'd suggest we change their color to make them far less prominent. 
- [x] Do we want to introduce the comment section in any way, i.e. "Add your own review of this product" or something like that. 

cc: @natalieworth @beccaklam @ScottDowne

**Comment by natalieworth** [comment]
Can we update the images for the header and the footer too (header takes a while for me to load cause it's not the down-sized version):
- [x] Header: https://drive.google.com/file/d/0B20-0lpP23c0U0xNNUpUMWRvM3M/view
- [x] Footer: https://drive.google.com/file/d/0B20-0lpP23c0cVdfdncwNDhaYkE/view

cc @ScottDowne

**Comment by HPaulJohnson** [comment]
A few more things on main nav: 

- [x] "M" logo is clickable but doesn't go anywhere
- [x] Once I'm off the home page, should we maintain some "*Privacy Not Inlcuded" branding in the header somewhere. There's not much context when I'm on one of the more detailed pages and it's possible that we'd send some traffic directly there.

**Comment by HPaulJohnson** [comment]
@ScottDowne Thinking about prioritization of the technical tasks still to be addressed, here's where I'd start: 

- [x] CSS changes
- [x] Investigating scrolling issues to see if configurations can be changed to improve performance. 
- [x] Change where/when the email popup triggers on the product detail pages
- [x] Update the "Does the company share data with a third party for unexpected reasons?" section to accommodate a single, one-word answer instead of a grid. 
- [x] Update "why we made this guide" template to match Natalie's design
- [x] Link the header logo back to homepage.
- [x] "Categories" breadcrumb should point to categories page (currently points to home page).
- [x] Make sure all the products link to the top of the product review page (vs. anchor/links in the middle of the review pages).

**Comment by ScottDowne** [comment]
@HPaulJohnson The first item, "CSS changes" is too much for one task and needs to be broken down a bit. I remember a lot of requested changes.

**Comment by beccaklam** [comment]
@ScottDowne based on QA ask to add the 'privacy not included' logo to subsequent pages. Designs for this: https://redpen.io/p/gr44a4589bde3fdc12 Basically when the user scrolls pass the large landing page with the title "privacy not included" could the logo transition to sit in the header?

@natalieworth Need to figure out mobile direction for this which is trickier given less real estate: https://redpen.io/p/gr44a4589bde3fdc12 (last three redpens) do you have a preference?

**Comment by beccaklam** [comment]
@ScottDowne Re: QA on making the landing page more conducive to scrolling/more action to get the user to scroll, could we animate the arrow like this: https://codepen.io/rightblog/pen/EagNMN?q=animated+arrow&limit=all&type=type-pens or like this: https://codepen.io/mfritsch/pen/VYdeEE?q=animated+arrow&limit=all&type=type-pens

**Comment by caltrider** [comment]
@ScottDowne On the tile category page it reads "Why we made the guide' and on the actual page with that story it reads "Why we made this guide."  Let's standardize to "Why we made this guide"

- [x] Change tile page box to read "Why we made this guide"

**Comment by TheoChevalier** [comment]
@caltrider On Friday I remember we wanted to update the categories on the homepage to use a verb, should we go with “Browse Game Consoles”, “Browse Home Hubs”, etc?

**Comment by caltrider** [comment]
Couple on things on the "Why we made this guide" page @ScottDowne @HPaulJohnson @beccaklam 

- [x] The font looks different on the list in the middle.
- [x] Add Links: 1. Link to our survey in the in the first graph where we say "then we did a survey".  I'll put that link in here tomorrow when we get that blog posted.  2. Link out to the Digital Standard when we talk about it in the Consumer Reports graph.  Here's the link to the Digital Standard: https://www.thedigitalstandard.org/

**Comment by ScottDowne** [comment]
We still have a dead link I need a link target for, which I was told is something @brettgaylor has?

@brettgaylor The site has a link for "Read more from our partners at Gizmodo and Univision" which I'm not sure where it should go, and I think people mentioned you had it? If not, sorry for the distraction.

- [x] Add link target to the "Read more from our partners at Gizmodo and Univision" link.

**Comment by caltrider** [comment]
@TheoChevalier Yes!  That works great for the categories. Please do that and let @ScottDowne and @beccaklam when they are ready to update.  Thank you!

**Comment by tlasadea** [comment]
@TheoChevalier @caltrider @HPaulJohnson here's the copy QA sheet I was talking about on the call: https://docs.google.com/spreadsheets/d/1Au0W0lMzUevwW8HDoGDMjx1gXshTA2Js77MDqUnMT0I/edit#gid=992855100

**Comment by TheoChevalier** [comment]
@tlasadea @caltrider @HPaulJohnson Copy has been updated with the latest changes in this ticket + the QA sheet, if there’s more just ping me

**Comment by HPaulJohnson** [comment]
Recap of outstanding items from our call this morning: 

**Site-wide**

- [x] provide OG meta tags copy (copy added in #1093) 

- [x] update OG mata tags into the site (Scott)

- [x] provide share images (design) note for @natalieworth: we can take the designs you've created for social marketing and add the "A holiday buyer's guide from Moz://a" tagline to them for these; 1 for Twitter and 1 for Facebook

- [x] provide Share Progress copy @ScottDowne [here is the copy deck](https://docs.google.com/spreadsheets/d/1nXLPHQt_z8Bp5gbLWVWgo_z7SQCKEyHU0NbvnYxuY8U/edit#gid=608119045). 

- [x] implement Share Progress content (Scott)

- [x] finalize  "Privacy Not Included" branding in the header on all subpages comps (design)

- [x] Implement "Privacy Not Included" branding in the header on all subpages (Scott)

- [x] Change "M" logo to full "Moz://a" wordmark in header

- [x] in breadcrumb navigation on subpages, make clicking on "category" take you to the full page category grid (instead of first category on homepage). 

**Homepage**

- [x] Make initial scrolling more intuitive by providing a "peak" of the intro to guide content and making the arrow animated to clearly communicate more content below the fold. (design and dev)

- [x] Move the italicized paragraph about Consumer Reports in intro to the bottom of page, directly below the category content. (note on this for @ScottDowne and @beccaklam - we could probably make the type a bit bigger now that it has it's own real estate at the bottom; also not sure if it still needs to be italicized). 

- [x] Remove red styling on links to make them less prominent (design and dev)

- [x] Make the categories more clearly clickable by adding "Browse [category]..." copy to each section.

- [x] for categories, swap the order and emphasis of existing section heading and subheads, and make the subheads "browse [cat]" underline to denote links. 
 

**Why We Made This Guide Page**

- [x] Update template to move content up and to match Natalie's design

- [x] Update copy on menu and page headline so they are consistent

- [x] Update font (per Jen's comment above) so that it is consistent throughout.

- [x] Add Links: 1. Link to our survey in the in the first graph where we say "then we did a survey". Here's the link for the blog post: https://medium.com/mozilla-internet-citizen/10-fascinating-things-we-learned-when-we-asked-the-world-how-connected-are-you-2c9601c36ef0 2. Link out to the Digital Standard when we talk about it in the Consumer Reports graph. Here's the link to the Digital Standard: https://www.thedigitalstandard.org/

**Product Category Pages**

- [x] Update type treatment to be consistent with rest of site

- [x] Style product photos to be consistent, have less white space

- [x] and less drop shadow.

- [x] Add copy above comments section to introduce that section. Copy should exist in properties files now.

**Product Pages**

- [x] Resize all photos

- [x] Hyperlink Product name and remove long link

- [x] De-emphasize "copy link" button by moving it down below review or as a text link below description

- [x] Rework checkmarks to better communicate positive/negative attributes and generally make these pages more scanable.

- [x] Add link target to the "Read more from our partners at Gizmodo and Univision" link.

**Comment by tlasadea** [comment]
On Safari (version 11.0) the CSS looks off and there is some weird stuff happening with the initial copy on the homepage. @ScottDowne @beccaklam @natalieworth 

![screen shot 2017-11-01 at 11 28 06](https://user-images.githubusercontent.com/30296602/32272867-ed423a32-bef7-11e7-876b-6951cf56dc65.png)

**Comment by ScottDowne** [comment]
@tlasadea thanks for pointing this out. I can look into it.

**Comment by caltrider** [comment]
On the category page with all the tiles, exercise is spelled wrong on "health & exercise".  
Also, on the product pages, should we capitalize Camera, Microphone, and Track Location?
cc: @ScottDowne @beccaklam @natalieworth @HPaulJohnson 

- [x] Fix spelling of "exercise" on health & exercise tile on category page
- [x] Capitalize Camera, Microphone, Track Location on product pages

**Comment by caltrider** [comment]
@ScottDowne Here are the links for the "Why We Made This Guide" post:

Link to our IoT survey blog post (in the first graph): 
https://medium.com/mozilla-internet-citizen/10-fascinating-things-we-learned-when-we-asked-the-world-how-connected-are-you-2c9601c36ef0

Link to the Consumer Reports Digital Standard (in the Consumer Reports graph): 
https://www.thedigitalstandard.org/

**Comment by beccaklam** [comment]
@ScottDowne Here's the redpen: https://redpen.io/p/gr44a4589bde3fdc12 for adding the "privacy not included" logo to the header for both desktop and mobile. You will also find the design for the updated review page in there. We decided to go with a "yes and no" system and using a red/green system to denote whether a yes or no is good or bad. Does that make sense? It may take some inferring on your part to figure out what is good or bad unless @caltrider @HPaulJohnson know of someone with capacity and knowledge who can go into the reviews and denote whether something is good or bad? cc: @natalieworth

**Comment by HPaulJohnson** [comment]
@beccaklam - these all look good to me. let's move forward with this direction.

**Comment by HPaulJohnson** [comment]
@ScottDowne i'm getting the scrambled text on scroll (per Temi's comment above) in mobile chrome as well.

**Comment by ScottDowne** [comment]
Safari stuff should be fixed.

**Comment by HPaulJohnson** [comment]
@ScottDowne that fixed it in mobile/chrome too.

**Comment by HPaulJohnson** [comment]
@ScottDowne note that I added a new, small change to the breadcrumb nav in the master list of outstanding updates above.

**Comment by ScottDowne** [comment]
@HPaulJohnson That might be tricky. The hamburger menu isn't a link, it's some js functionality. (which is how we get the transition) that you can toggle on and off. I cannot make a link work like it and still work like a link.

**Comment by natalieworth** [comment]
Images are here: https://drive.google.com/drive/u/0/folders/0B20-0lpP23c0NXJXMTRUSGRTV3M

**Comment by HPaulJohnson** [comment]
Per our call this a.m., here's the final list of things that will carry us to the homestretch: 

**P1**
- [x] Implement @ScottDowne's change to improve scrolling behavior on homepage

- [x] Update images in Share Progress for social sharing buttons. Need @natalieworth to export final FB & TW versions and for @ScottDownewne to host somewhere we can link to via URL. 

- [x] Update OG tags with new copy and social share images. 

- [x] Apply type treatment styling to *Privacy Not Included header

- [x] Fix *Privacy Not Included header in mobile/potrait mode

- [x] Update product images on all category and product detail pages with resized photos. 

- [x] On Product detail pages, update "What Does It Know About Me?" section using alternating grey/white row style to match "Can It Spy On Me?" section styling. 

- [x] Swap order of "Privacy Policy" and "What Can Happen If Something Goes Wrong" content at bottom of product reviews.

- [x] Apply header styling to "Got Questions?" copy above Coral 

- [x] Update "Contact Us" target to point to general MoFo support email queue (advocacy@mozilla.com). 

- [x] Add link target to the "Read more from our partners at Gizmodo and Univision" link. (link to: http://www.univision.com/seguridad-online)

- [x] Fix link target for Digital Standard in consumer reports footer on homepage to point to: https://www.thedigitalstandard.org/

- [x] Update "Share this page" link target in footer to point to: http://share.mozilla.org/352/184264

**P2**
- [x] Use full "Moz://a" wordmark in header for desktop view

- [ ] Adjust placement and styling of Consumer Reports partnership disclaimer at bottom of homepage

- [x] In breadcrumb navigation on subpages, make clicking on "category" take you to the full page category grid (instead of first category on homepage).

- [ ] Apply additional styling to "What Can Happen If Something Goes Wrong" content at bottom of product reviews to add emphasis given importance of this copy in the overall hierarchy of the reviews. 

- [ ] Find a better placement for "copy link" button on product reviews so it isn't on the same line as the "Safety Review" headline. Actually think it might work at the very bottom of the review, as a way of separating the product review piece from the additional content and coral parts of the page. 

cc: @ScottDowne @beccaklam @natalieworth @caltrider

**Comment by HPaulJohnson** [comment]
@ScottDowne created ticket #1096 to track progress moving this site to staging, then production.

**Comment by HPaulJohnson** [comment]
- [x] @ScottDowne link target for "Read more from our partners at Gizmodo and Univision" on our product review pages should be: http://www.univision.com/seguridad-online

**Comment by brettgaylor** [comment]
- [x] Hi - seeing another odd CSS error, this time in chrome. Here's a screencast
https://www.dropbox.com/s/7a4b20zjkfputc6/css%20bug.m4v?dl=0

**Comment by beccaklam** [comment]
- [x] @thecount When navigating to a category page from the landing page cateogry 'sections' the category page loads in the middle of the page instead of the top:
![bg-wa-category-page-load](https://user-images.githubusercontent.com/20977376/32355185-a6ee82b8-c003-11e7-876a-9adb8b918c30.gif)

**Comment by natalieworth** [comment]
- [x] @ScottDowne Uploaded the 2 thumbnail images for 'Home' and 'Why We Made This Guide' in here https://drive.google.com/open?id=0B20-0lpP23c0bHdkR19CekZKVnM

**Comment by HPaulJohnson** [comment]
- [x] Added to master list above, but "Share this Page" link in footer should point to a Share Progress landing page. Created one here for now: http://share.mozilla.org/352/184264
- [x] Need a Spanish one too.

**Comment by natalieworth** [comment]
Share progress images are here https://drive.google.com/drive/folders/0B20-0lpP23c0SGZGYTA2Ul9abFk?usp=sharing

**Comment by HPaulJohnson** [comment]
thanks, @natalieworth already updated share progress buttons with these. 

- [x] @ScottDowne can you also include these in the OG tag updates in #1093

**Comment by TheoChevalier** [comment]
- [x] On Spanish pages, the share buttons should be using those strings, but they are using English strings
https://github.com/mozilla/advocacy.mozilla.org/blob/master/buyers-guide-locales/es/share.properties

**Comment by HPaulJohnson** [comment]
- [x] On mobile, "browse [category]" links on homepage are no longer clickable on staging.

**Comment by HPaulJohnson** [comment]
- [x] Missing product blurb for Nest Cam Indoor Security Cam: https://advocacy.mofostaging.net/en-US/privacynotincluded/category/smarthomeaccessories/nestcamindoorsecuritycamera
**Théo:** typo of mine, good catch! Fixed here https://github.com/mozilla/advocacy.mozilla.org/commit/99d7143293f323d62d923b4c0e277c810a8318ad

**Comment by HPaulJohnson** [comment]
- [x] Update link to manufacturer website on Automatic Pro product review (currently links to Google Home).

https://advocacy.mofostaging.net/en-US/privacynotincluded/category/gadgetsgizmos/automaticpro

**Comment by ScottDowne** [comment]
- [x] post signup share buttons are not responding to clicks.

**Comment by HPaulJohnson** [comment]
- [x] Facebook share is still showing old (Safety First) content

**Comment by ScottDowne** [comment]
Yeah, I dunno what's up with that. I know facebook is a cache monster, but this is a little much.

**Comment by natalieworth** [comment]
There's design QA I'm putting in the redpen here. The site's looking good, but I feel like it's pretty important to have a good landing page. It'd be ideal if we still have a bit of time in the morning for me and @beccaklam  to do a final design pass with @ScottDowne  to fix all outstanding design issues. Essentially it's just landing page, category page, and individual product page. I'm not anticipating it to be a ton of work—but I feel like it will make a huge difference. 

cc @HPaulJohnson

**Comment by HPaulJohnson** [comment]
i'm assuming we can still go live _and_ continue to make these final refinements in the a.m. there's a bit of early marketing happening tomorrow (hence needing the URL live) but the real volume won't come until next Tuesday. i'd assume that we have between now and e.o.d. Monday to get everything perfect. 

overall, it's looking really great. kudos to you all.

**Comment by natalieworth** [comment]
I think we've got an hour in the morning before it goes live, so should be okay! Yeah, then would be awesome if we could refine for the official Tuesday launch.

**Comment by caltrider** [comment]
@ScottDowne  @TheoChevalier Just shared the site with legal on slack and noticed the pull graphic for the spanish site is in english. Not sure if that's only on Slack or not.

- [x] Check that the pull graphic for the spanish site is in spanish

**Comment by caltrider** [comment]
@ScottDowne @TheoChevalier I see Janice updated the evaluations of two products:
The Sphero SPRK+ and the Sphero BB8 (in the product review doc, they are on Janice1, columns P and Q. She updated the camera/microphone/tracks locations bits (just those, nothing else in the review changed). 

Here's the product review doc: https://docs.google.com/spreadsheets/d/1szZeBKAib8n3QOKZ6Th5ao3XrJr8CDdD9VDL6t6Tgyo/edit#gid=1402744990

**Comment by caltrider** [comment]
The good news, I've reviewed over half the products and everything is looking great. The bad news, I finally found a typo @TheoChevalier @ScottDowne. On the Meural Canvas under the _What could happen if something went wrong?_ it currently reads:  It could use the ambient light sensors the comings & goings in your household.
It should read: It could use the ambient light sensors to know the comings & goings in your household.

**Comment by ScottDowne** [comment]
- [x] The post signup page "No thanks" link is missing a translation, and is displayed as "no_thanks"
- [x] update the evaluations of two products The Sphero SPRK+ and the Sphero BB8
- [x] Fix the typo in " It could use the ambient light sensors the comings & goings in your household"

**Comment by caltrider** [comment]
On the gadgets product page the Hiku image looks stretched and funny.  https://advocacy.mozilla.org/en-US/privacynotincluded/category/gadgetsgizmos

- [x] Fix the sizing of the Hiku image on the gadgets product page
- [x] Fix sizing of the pet cube too (it's in same category)
- [x] Fix sizing of Nest Cam Outdoor Security on the Smart Home Accessories page
- [x] Fix sizing of the Spire on the Health & Exercise category page

**Comment by natalieworth** [comment]
The Tile Sport is displaying off center. I updated the image here https://drive.google.com/file/d/0B20-0lpP23c0X2FwM1FNSEJYbkU/view
- [x] Update the Tile Sport image

**Comment by caltrider** [comment]
The image on the MocaCuff is a MocaHeart, not the MocaCuff:  You can find the MocaCuff below the MocaHeart here on this page:  https://www.mocacare.com/media.html
@natalieworth @ScottDowne @beccaklam 

- [x] Change the MocaCuff image to the right one

**Comment by caltrider** [comment]
This popped up for Abigail the lawyer when she did her review of the site.  I could replicate it. Anyone else getting this?  
QA: When I click on “Why we made this guide,” I’m automatically directed to the bottom of the page.

- [x] Check to make sure when you click on "Why we made this guide" it take you to the top of the page, not the bottom

**Comment by caltrider** [comment]
Janice is updating some of her product reviews in the review doc. What's the best way to highlight those?

**Comment by caltrider** [comment]
@ScottDowne @TheoChevalier 
Janice has marked the products in the product review doc in orange that she has updated. Looks like there is about 11 of them so far. I'm marking the products I've QAed in purple.  Once you update these, could you switch the orange highlight so something else (blue or green) so I know which ones have been done and can go back in and QA those?

- [x] Update product reviews based on Janice's updated reviews

Link to Product Review Doc: https://docs.google.com/spreadsheets/d/1szZeBKAib8n3QOKZ6Th5ao3XrJr8CDdD9VDL6t6Tgyo/edit#gid=1402744990

**Comment by caltrider** [comment]
@ScottDowne On the Weber iGrill2 product, we link out to the wrong website (we like to the iGrill3, not the 2).  
Here's the correct link: https://www.weber.com/US/en/accessories/igrill-thermometers-timers/igrill-2

- [x] Swap the website link on the Weber iGrill to the correct one

**Comment by HPaulJohnson** [comment]
- [x] @ScottDowne Spanish versions of Share Progress buttons and "Share this Page" page are here: 

FB Button: `<div class='sp_184294 sp_fb_small' ></div>`
Twitter Button: `<div class='sp_184295 sp_tw_small' ></div>`
Email Button: `<div class='sp_184296 sp_em_small' ></div>`
Share This Page: http://share.mozilla.org/352/184298

@TheoChevalier one issue with the "Share This Page" page (which is linked to from the footer), is some preset text that is controlled by Share Progress and not customizable (and therefore localizable). Specifically: "Your Almost Done," "Step One: Email," "Step Two: Facebook," and "Other Ways to Share." In your opinion is this a big deal (obviously not ideal); if it is we might need to remove this option from the footer for the ES version of the site.

**Comment by beccaklam** [comment]
- [ ] I don't know if this is just a browser thing but having trouble clicking the hamburger button in mobile view on the category pages and the item pages. As in 90% it doesn't work. @ScottDowne

**Comment by caltrider** [comment]
Typo Alert @TheoChevalier 
_On the Philips Hue White & Color Ambiance Starter Kit. The first line of the blurb reads:_
Lights that dance with your music, jump with your movies, or pound with your videos games — 

It should read:

Lights that dance with your music, jump with your movies, or pound with your video games — 

_And this typo too on B&O Play Speaker:_
Right now under What Could Happen if Something Went Wrong it reads:
It could let people can guess who is at home based on what music is playing.

It should read: 

It could let people guess who is at home based on what music is playing.

- [x] Fix typo on Philips Hue light bulb blurb
- [x] Fix typo on B&O Play Speaker "what could go wrong" blurb

**Comment by caltrider** [comment]
@ScottDowne I think we're missing a product.  I don't see the Hatch Baby Rest in the guide (it should be under Smart Home Accessories)

- [x] Add the Hatch Baby Rest product to the guide

**Comment by TheoChevalier** [comment]
> @TheoChevalier one issue with the "Share This Page" page (which is linked to from the footer), is some preset text that is controlled by Share Progress and not customizable (and therefore localizable). Specifically: "Your Almost Done," "Step One: Email," "Step Two: Facebook," and "Other Ways to Share." In your opinion is this a big deal (obviously not ideal); if it is we might need to remove this option from the footer for the ES version of the site.

Yeah, not ideal but I think it’s okay. Even if they don’t speak English at all, it should be easy enough to guess what they can do on the page, especially with the icons

**Comment by caltrider** [comment]
Heya, just noticed this typo reading your comment @HPaulJohnson and @TheoChevalier .  It should be "You're Almost Done". 

> @TheoChevalier one issue with the "Share This Page" page (which is linked to from the footer), is some preset text that is controlled by Share Progress and not customizable (and therefore localizable). Specifically: **"Your Almost Done,**" "Step One: Email," "Step Two: Facebook," and "Other Ways to Share." In your opinion is this a big deal (obviously not ideal); if it is we might need to remove this option from the footer for the ES version of the site.

**Comment by TheoChevalier** [comment]
That’s only on GitHub, the real string does not have the typo https://share.mozilla.org/352/184264

**Comment by beccaklam** [comment]
<img width="387" alt="screen shot 2017-11-06 at 1 50 38 pm" src="https://user-images.githubusercontent.com/20977376/32458187-95e3345c-c2f9-11e7-9d2e-4ffd1dd689c8.png">

- [ ] @ScottDowne In browserstack (iPhone 6, chrome) and on an iPhone 5 ('chrome') the mobile browser rendered the header cut off.

**Comment by caltrider** [comment]
@ScottDowne @TheoChevalier @HPaulJohnson The spelling of exercise got fixed on the category page but it's still spelled wrong on Health & Exercise when you scroll through the product categories.

- [x] Fix the spelling of exercise on the category scroll

**Comment by TheoChevalier** [comment]
This one’s on me, forgot we had two strings. Now fixed!

**Comment by HPaulJohnson** [comment]
thanks again to herculean efforts by all, nearly all of these bugs and enhancements have been squashed and none of the open issues are blockers for launch. 

Given how unwieldy this issue has become and because we have now launched to production, I'm closing this ticket. 

If you identify new bugs that need fixing please put them in the newer issue, #1100 

If you have suggested enhancements for future versions of the site you can create a new ticket for those.
