### ISSUE TITLE
Remove old GA tags from links on "Ways to give" donate page

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#1089]
Detailed description of work:
Just noticed that on our ways to give page, https://donate.mozilla.org/ways-to-give , there are a lot of links there with outdated Google Analytics tags.  Can we please remove these so our reporting is more accurate?

1. Specifically, the first link at the very top -- "Go to this link to make a secure ..." ... links to:
https://donate.mozilla.org/&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=wiki.mozilla.org&utm_medium=referral&utm_content=Ways_to_Give
....
which should just be:
https://donate.mozilla.org/?utm_content=Ways_to_Give

2. Also, down lower, we have several dozen currency links, for example the CAD one:
https://donate.mozilla.org/?currency=cad&ref=EOYFR2016&utm_campaign=EOYFR2016&utm_source=wiki.mozilla.org&utm_medium=referral&utm_content=Ways_to_Give

.... that just needs to be ...

https://donate.mozilla.org/?currency=cad&utm_content=Ways_to_Give

(this change needs to be made to all ~40 currencies listed there.)

Thanks!

*Start date: October 21, 2017* 
*Due date: November 1, 2017* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @cadecairos @shaghdoosti

**Comment by TheoChevalier** [comment]
Fixed in https://github.com/mozilla/donate.mozilla.org/commit/a5e7e74978424731b7c9a00bc933a837b1d632db also made sure to reject any pending suggestions in Pontoon that have the old tracking link.

Noticed in the process that we also have this one:
https://donate.mozilla.org/give-bitcoin/?ref=EOYFR2016&utm_campaign=EOYFR2016&utm_source=Wiki_WaysToGive&utm_medium=referral
(very last link of the ways to give page in the Bitcoin section).
Do we want something else here?

**Comment by ScottDowne** [comment]
This got done, thanks @TheoChevalier you're the best.
