### ISSUE TITLE
Clone of donate page for campaign-specific fundraising

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#1117]
Detailed description of work:  We need to create a clone of the donate.mozilla.org donations page, so that fundraising efforts specific to our Data privacy and security efforts can be better tracked (thus helping us meet OKR 3.3).  The best model here is probably the "Glass Room" donations page that was created last year (?).  All functionalities of the primary donate page should be the same on this new version, and funds donated go to the same place.  Vojtech is the best expert for specifically what parameters/attributes of the new page need to be changed in order to enable the distinct trackability we need.

*Start date: February 15, 2018* 
*Due date: March 1, 2018* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @shaghdoosti @ScottDowne

**Comment by alanmoo** [comment]
@WillatMozFdn Can you file a project brief to get this on our roadmap? https://mzl.la/project-brief

**Comment by jessevondoom** [comment]
I have a few questions and need to point out a few things:

1. Does this need to have a custom data/privacy/security design or should it look the same?
2. If the design can look largely the same, is there any reason we can't accomplish tracking using a querystring instead of a clone? I kind of hate the idea of making multiple clones of the site — it could lead to bugs being fixed in one location and not another, doubles devops overhead, etc. 
3. Could you fill out this project brief so we get it into our job review queue? [https://mzl.la/project-brief](https://mzl.la/project-brief) 

Couple other things:
1. This is a really tight deadline, effectively asking us to drop current work in order to get this done. We're working to establish better processes, but please understand that we carry a pretty full workload and run in two week sprints — so please let us know if March 1 is what you're hoping for or what you need. And in the future let's try to get these things sorted with a lot more runway.
2. I'll reach out directly, but I'd like to have a conversation about small dollar fundraising tech needs. In this example you've come to us with a specific solution in mind, but I think it's worth evaluating build-out around embedded donation forms/buttons and/or the querystring approach I talked about above. Bottom line: I'd like to have a higher-level conversation about your needs so we can support you better as a team going forward.

**Comment by ScottDowne** [comment]
@jessevondoom I can answer #2.

They way we do this is by creating a new route, and just applying some of the same components to it. So it's not really a clone on our end of this, just a similar looking page on a new route, using a lot of the same components. In this case, it'll probably be all the same components, with one flag to pass in a tag to go on the donation as it's submitted. The functionality for passing in tags mostly exists, we just need to add another check on the back end for the new tag.

**Comment by WillatMozFdn** [comment]
Thanks fellas!  Some answers ...

@jessevondoom ... your questions part A:
1. Will look exactly the same design and layout-wise but likely have different copy over on the left side.
2. I need to loop in @vojtechmzl to answer the question of why this is better done with a separate page and not just using good & consistent tagging practices.  
3. Sure, totally happy to do so, I respect process!  (But need to get Vojtech's input on #2 there before I can do a good job on the project brief.)

Part B:
1. No, that's a hoped-for deadline chosen by tossing a dart at the wall, not a must-have.  We'll work with your capacities.
2. Absolutely -- yes, let's connect directly, I can't answer all those questions for you just yet, but some things are shaping up so a preliminary conversation wit you would be super-helpful.

**Comment by vojtechsedlak** [comment]
The reason we were thinking of cloning the donate page, similarly to what we are doing with thunderbird and what we did with glassroom, is the ability to find and track the campaign donations in Stripe and Paypal. While query parameters would be sufficient in marking things in GA, since we are not currently passing full URL + parameter data along to the payment processors, there would be no way of distinguishing them.

**Comment by WillatMozFdn** [comment]
Closing -- we're not moving forward with this.
