### ISSUE TITLE
EU Copyright Petition: Create User Data Plan

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#153]
We need to make some decisions about what personal data is being collected and where it is stored. 

See #115 for more information about Petition signatures and messages. 

@valianttry @ScottDowne @a-kilroy

**Comment by ScottDowne** [comment]
I'm coming from the other ticket.

Maybe it'll help if I say why I'm asking where can we put the data.

My main concern revolves around can we salvage a petition without BSD or nationbuilder. (I'm thinking Murphy's law here and being a pessimist)

Right now I have no clue about the requirements (not technical requirements) for storing signatures. It's always been inside a framework (BSD or nationbuilder)

It just goes into the system, and magically, someone sends it along to someplace.

What can we use without one of these systems that we already have access to?

Can we, in a pinch, just store it in a google sheet? (and salesforce)

**Comment by damiankay** [comment]
I think this is an important question, and as I don't have an answer, I'm CCing @simonwex @drewmoto as well.

**Comment by ScottDowne** [comment]
I think based on the call we had, and some of the info in this ticket: https://github.com/MozillaFoundation/Advocacy/issues/115

I think I now have the answers I needed. In a pinch, for phase 1, we can use anything to store the signatures, just so long as we can export it, and it's the fields we need.

Phase 2 is more complex, because we need a digital solution, and real time submission, but let's not solve that here.
- [x] what we're storing: https://github.com/MozillaFoundation/Advocacy/issues/150
- [x] where we're storing it: hopefully nationbuilder, if not, google sheets, for phase 1.

Closing.
