### ISSUE TITLE
Treatment for first explainer video

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#156]
Work with Darren to produce a treatment for the video that will launch with the first iteration of the campaign website.

Due: July 29th

**Comment by KevZawacki** [comment]
Hi @brettgaylor, I've just read through the [script](https://docs.google.com/document/d/1XwH-IJYKNBW2leiOc_kmtIlI4u4VM0sFoCAmjmst9dE/edit) for video 1. My initial thoughts:
- I really like it. The storytelling is almost entirely visual, and the narration almost perfunctory. That's great, given the multilingual audience
- Even so, the narration copy is really powerful and accessible. We can riff on it for social assets 
- The one part that comes across as a bit vague: "Instead, copyright laws that regulate how we share online **are written for a time when it was actually hard to make a copy of something**." Can we clarify? Maybe add another line like, "These are laws that were written when the postcard, not the iPhone, was the primary way of saying hi from a distance; when cameras didn’t fit in our pockets; and when “gif” hadn’t yet infiltrated the Oxford English Dictionary."

Also, my thoughts on how this script aligns with our current [petition copy](https://docs.google.com/document/d/1SirP8cG_33HqEsnN-xizFpQBZvjv5pG7r51TlwxW_V8/edit): 
- They do work together. To me, video = heart and petition = brain. But the tone is very different
- The video should precede the petition, like an introduction. Otherwise it seems backward
- I like Jordan's idea of inserting visual elements from the video (the pug, the reaper) into the copy, to further tether them together

cc @HPaulJohnson

**Comment by brettgaylor** [comment]
Treatment approved!
