### ISSUE TITLE
EU Copyright Campaign: v2 website UI

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#204]
Design petition v2 website UI based on #203

_Start date: August 29, 2016_
_Due date: September 6, 2016_

CC:
@natalieworth @damiankay @lovegushwa

**Comment by damiankay** [comment]
Hi @beccaklam - we need to provide internally approved designs to Fission by September 6. Please let me know if you think this is overly aggressive. 

They've requested them in PSD format, and asked that you use German or Polish in comps if possible.

**Comment by beccaklam** [comment]
@damiankay Hi Damian, is there any way they can work with a sketch file? Just wondering, it would be much less work on my end and given the tight timeline that would be wondreful. Maybe ask if there's any work arounds? Also, would I be able to get a file (e.g. a google doc) with the German and Polish version of the petition? That would be preferable instead of just copying and pasting off the site :)

**Comment by damiankay** [comment]
@valianttry do we have a Google or Word doc with the translated petition copy for @beccaklam?

**Comment by damiankay** [comment]
@beccaklam - they don't use Sketch, unfortunately. Is there a tool to convert sketch files to PSDs?

**Comment by valianttry** [comment]
@damiankay we used Pontoon for localization, so no there is no clean Google doc with the localized copy for Tier 1 locales. Polish is in Github (it's an outlier). 

Does @beccaklam  just need it to check the design / fit / layout? She can probably find strings in Pontoon for that purpose, but we should purge all dummy copy before we go live: https://pontoon.mozilla.org/en-GB/mozilla-advocacy/Copyright%20Petition/?string=154336 

We had a professional localizer copy/paste all the translations from Pontoon > Nationbuilder because the risk of error is high (in other words, i don't recommend Rebecca do that herself).

**Comment by damiankay** [comment]
Thanks @valianttry - who's the best person to purge the dummy copy? Rebecca is trying to get moving on this as we have a deadline to hit for V2 if we want to stay on schedule (despite having to focus on V1 launch).

**Comment by valianttry** [comment]
I'm confused. All the localizations are already loaded up in Bablic for the petition and all associate content. Will we have to a) do that all again for V2 or b) can we just re-use what's in Bablic? I'm SO hoping the answer is B.

**Comment by natalieworth** [comment]
@beccaklam Here are some screen shot examples from the CSI gif too! They still have shutterstock over them and may change in terms of tone, but I'll update when we have a more refined draft:
<img width="1003" alt="screen shot 2016-08-30 at 1 20 19 pm" src="https://cloud.githubusercontent.com/assets/14876567/18105592/d4dcef76-6eb4-11e6-8cee-7f646c6a731c.png">
<img width="1012" alt="screen shot 2016-08-30 at 1 20 58 pm" src="https://cloud.githubusercontent.com/assets/14876567/18105597/d6eec17c-6eb4-11e6-9cdc-85dabe13f02e.png">

**Comment by beccaklam** [comment]
@lovegushwa @valianttry @HPaulJohnson  cc: @natalieworth Hi Andrea and Paul, here is a link to the red pen containing the Copyright Campaign's V2 microsite: https://redpen.io/p/jt5d4848f80e902f79 We need to ship the finals to Fission by Thursday in order to give them enough time to build. Jordan is on PTO after Wed (tomorrow) so he'd like to sign off on a design by then. Would you be able to take a look and let us know if there are any changes that need to be made?

**Comment by beccaklam** [comment]
@valianttry @damiankay Sorry for the fuss! I do just need to check layout and design so I'll just copy and paste from the current microsite, seems easiest for everyone. Also, @damiankay I'll just build out the file in Photoshop, hopefully tomorrow.

**Comment by damiankay** [comment]
Thanks @beccaklam - appreciate it. Let's keep these issues in mind and try to resolve for the next project so that we can make things run a bit smoother for our team.

**Comment by damiankay** [comment]
Hi @beccaklam - just wanted to confirm which formats you're setting up for Fission. Will they have tablet and mobile as well? 

CC @lovegushwa

**Comment by beccaklam** [comment]
Redpen V2 UI Finals: https://redpen.io/p/wb0c491a132dbd6c24
Google drive: https://drive.google.com/open?id=0BzuBOR2VJQqUc29FMjk4VnM3UTQ

**Comment by damiankay** [comment]
Closing this - great work!
