### ISSUE TITLE
Maker Party website: Create visual design of website UI and brand assets in Nationbuilder

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#235]
Design for pages on Nationbuilder will be handled by Fission. 

Detailed description of work:
Design should be based on:
Required functionality #75
Site map #126

Fission will provide designs in InVision for direct feedback by Mozilla.

Due date: August 22

CC: @ScottDowne @geroter @lovegushwa @HPaulJohnson

**Comment by damiankay** [comment]
Here is the first round of UI designs for the Maker Party events pages from Fission: 
- Desktop: https://invis.io/G78C7AR2E
- Mobile: https://invis.io/J98HLYNB6

Please review and leave comments below (I.e. in this GH issue)
@lovegushwa @HPaulJohnson @shaghdoosti @geroter @a-kilroy

**Comment by geroter** [comment]
Looks really excellent.

My only comment at this point is to see how in the event sign-up flow we can:
1) Help people be really intentional about thinking about the goals they have for the event.
2) Drive people toward the packaged activities, and having that as part of the event host process.

Some ideas:
- have the host kit or some link to activities in the flow of setting up an event
- have a drop-down box in the event setup where people select which activity they will be running (and of course an option for "my own activity")
- have some initial text in the event description box
- have a second (not public visible) text box to get people to write down some goals they have for the event
- have some kind of email trigger (or even a personal reach-out could be amazing and maybe doable) right after people setup an event to encourage goal setting and these activities

**Comment by lovegushwa** [comment]
@damiankay looks good overall. The colors are all slightly off (blue, teal) ... Teal should be: 00afb5 and blue: 2D4A8C  
<img width="897" alt="screen shot 2016-09-06 at 7 06 28 pm" src="https://cloud.githubusercontent.com/assets/12228435/18297684/57af4d24-7467-11e6-8c09-ec3327ce5b06.png">

https://learning.mozilla.org/en-US/events

**Comment by damiankay** [comment]
Thanks @geroter & @lovegushwa - I've shared this feedback with Fission.

**Comment by damiankay** [comment]
@geroter please see Fission's response to your requests below: 
For Goals & Activities:
1.  Yes, we can add a link to the Host Kit in the sidebar
2.  Is this only displayed in the back-end or are you looking to display the output on the front-end as well? (I.e. the activity drop down selection)
3. Yes, we can pre-populate text - what do you have in mind? 
4. This can't be done (second text box to enter goals)
5. Yes, this can be set-up (email trigger)

**Comment by damiankay** [comment]
@geroter @lovegushwa @a-kilroy 

The Maker party events page designs have been updated. Please have a look at the comps at the links below. You can leave comments directly in InVision by clicking the "comments" slider in the lower left corner. 

Desktop: https://invis.io/G78C7AR2E
Mobile: https://invis.io/J98HLYNB6

We should send feedback by 10am Friday Sep 9 (PST). 

Thanks!

**Comment by damiankay** [comment]
Hi @geroter @a-kilroy @lovegushwa @shaghdoosti 

Please see updated UI designs here: 
- [Desktop](https://invis.io/G78C7AR2E)
- [Mobile](https://invis.io/J98HLYNB6)

Fission has made the following changes:
1. on event list, changed sidebar call out button copy to: Sign Up to Host an Event
2. created additional screen to show activate account form 
3. on host an event form, removed ticket price section
4. added #makerparty to all tweet TAF boxes
5. fix "mozzilla" typo in all footers

We're waiting on confirmation for two other changes depending on whether they are supported in NB:
1. Remove social login 
2. Change miles to kilometers

**Comment by damiankay** [comment]
Confirming that the social login is being removed. 

Unfortunately, they are not able to change miles to KMs. It's a limitation of the embedded map technology that is built into Nationbuilder.
