### ISSUE TITLE
Maker Party: Wireframes review

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#255]
Detailed description of work:
Here's the link to the Maker Party wireframes: https://invis.io/G78C7AR2E

There are two options:
1. The first follows the mock-ups that were shared 
2. The second takes a slightly different approach with a full size header image of a map

Please capture feedback here initially so that we can provide Fission with a unified response. Once we have aligned on our feedback we can add it directly to the wireframes by turning on comments in the bottom right hand corner of the mock-up. 

Feedback due: Monday August 22 EOD

CC: @geroter @shaghdoosti @chrislarry33

**Comment by shaghdoosti** [comment]
George, Sara and Chris to have an initial look and then come back to the team.

**Comment by damiankay** [comment]
Here is a link to the updated screens in InVision:
https://invis.io/G78C7AR2E

They’ve separated the two approaches; you can see them separately by starting at the overview page listed above. 

Flagging that we need consolidated feedback from the leadership group by the noon August 23 PT. 

Thanks!

**Comment by geroter** [comment]
Hey team ... I'll drop thoughts in here directly.

1) On the landing page feels like the CTA might be below the fold, especially on mobile. I know that we want great imagery upfront, but perhaps we also want CTA buttons on that top image.

2) Host landing page -- same comment re: CTA ... having this below the activities I think will be a confusing user experience as browsing those might actually feel like what you're supposed to be doing on that page (rather than "get started")

3) Event listing page -- excellent. I would note most of the world/Europe doesn't use "miles" as a measure, so we might want to reconsider how we talk about that. 

_Also RSVP is a very **not** globalized term (needs to change through/many pages). I would instead switch to "attend" or something of the sort._

4) Sign in -- this is probably a longer conversation about what services we will enable for login ... I would like Simon to weigh in on this

5) Host form to setup an event -- will this be editable after entered by the host? If so, it could be good to have 2 added pieces --> 1) activities that you will run, 2) goals (#s and maybe even learning outcomes) ... I'd like to test how much we can trigger people to be thinking about this in advance ... not sure whether this would reduce completion, and suspect it would increase quality

6) Event host finished -- can hosts bulk sign-up people, or only invite?

**Comment by a-kilroy** [comment]
Agree with George's comments, esp about the CTA.

I'll also say that we might want to avoid RSVP numbers since displaying low
numbers can actually hurt recruitment. Maybe using ranges that trigger
something as an indicator. For example:
1) Just Added! (under a week old)
2) Taking off (1-10 rsvps)
3) Heating up (10-20 or 50% of limit or another indicator)
4) Almost full

**Comment by damiankay** [comment]
@geroter is there any preference between the two approaches? One is closer to the learning.moz layout, with the sidebar, but this is more difficult to achieve in Nationbuilder. I believe Fission's preference is to go with option 2, with a more standard header / footer treatment. 

BTW, if you click on the 9-square icon at the bottom left of InVision, you can see the separation between the two versions more clearly. Otherwise it's hard to tell where one ends and the other begins! 

CC @shaghdoosti @chrislarry33 @a-kilroy @lovegushwa

**Comment by geroter** [comment]
@damiankay  Totally missed the second set!

I actually prefer Option 2 for this because I do believe this campaign, while connected with learning.moz activities, is quite distinct.

No idea how Option 2 would be implemented, but I'm not a major fan of the solid horizontal header line (personal preference).

**Comment by damiankay** [comment]
Thanks @geroter - passing the feedback on to Fission for wireframe revisions.

**Comment by damiankay** [comment]
@simonwex - can you please see @geroter's comment Re sign-in? 

> this is probably a longer conversation about what services we will enable for login ... I would like Simon to weigh in on this

**Comment by lovegushwa** [comment]
Re. option 2. It's important that the Maker Party events site feel more like a general Mozilla web app and less like it's the Maker Party website. I think we could do this by simplifying the header and possibly the footer. This gives us the flexibility to adapt it for other non maker party events in the future, and keeps the look and feel generic enough to work with a stand alone Maker Party site if we want one down the line.

Fundraising takes a similar approac: https://donate.mozilla.org/en-US/
We can send folks to the fundraising site from all different kinds of other campaign sites with out any worry about styles clashing, or confusion about still being on a campaign site ... The user clearly knows they are now visiting a donation form.

CC @damiankay @jendc123

![events](https://cloud.githubusercontent.com/assets/12228435/17984071/a4fe379a-6ac4-11e6-9f28-f6a7d1b4e96e.png)

**Comment by damiankay** [comment]
Hi @geroter @shaghdoosti @lovegushwa @a-kilroy 

Reminder that we need your wireframes feedback. The deadline for comments is tomorrow EOD PST. After that, any changes will result in delayed launch. 

Please see wireframes here: https://invis.io/G78C7AR2E

Also, please see some specific questions RE functionality here: #310 

Thanks,

Damian

**Comment by jendc123** [comment]
Hi @damiankay - wanted to confirm we have all feedback.  We are going to move into v1 design today.

**Comment by damiankay** [comment]
Hi @jendc123 - yes, please proceed. Note: Jordan left a few comments above RE simplifying the header. Can you please make sure that these are addressed in the designs? Thanks

**Comment by jendc123** [comment]
Hi @damiankay and @lovegushwa we will use the header suggested above in designs

**Comment by jendc123** [comment]
Hi @lovegushwa do you have a logo file for the Mozilla Maker Party event logo show in the mock-up above?
