### ISSUE TITLE
Software Update Email Review

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#34]
Please review the email copy, test the link and note any feedback in this ticket.

Audience: Anyone who took action on the encryption campaign (ie: opened an encryption campaign email) - ~691,000

**Comment by HPaulJohnson** [comment]
@stephaniemcv I'm not really getting the subject line. I'm assuming it's a play off the "not one's cup of tea" idiom but it's unclear and not paid off in the body copy in any way.

**Comment by stephaniemcv** [comment]
@valianttry @shaghdoosti @mmika

I agree with @HPaulJohnson about the subject line. I actually thought it was alluding to grabbing a cup of tea and enjoying the quiet time while everything updated. We need to clarify or connect it to the copy as it may come off as being click-baity.

**Comment by lovegushwa** [comment]
@stephaniemcv just a few small type fixes:

**A missing em dash**
<img width="608" alt="screen shot 2016-05-18 at 2 12 13 pm" src="https://cloud.githubusercontent.com/assets/12228435/15375227/d616d25c-1d02-11e6-8417-1396400b41af.png">

**Another missing em dash**
<img width="615" alt="screen shot 2016-05-18 at 2 12 23 pm" src="https://cloud.githubusercontent.com/assets/12228435/15375234/d933c030-1d02-11e6-8c99-4711021ece55.png">

**The link typeface does not match the body copy typeface**
<img width="666" alt="screen shot 2016-05-18 at 12 54 07 pm" src="https://cloud.githubusercontent.com/assets/12228435/15375247/e914fe92-1d02-11e6-9793-64b52482a0ce.png">

**Could add some line breaks between these sources so they don't all run together like one weird giant link. Also this sources link type size could be maybe %75 the body copy size**
<img width="632" alt="screen shot 2016-05-18 at 2 12 44 pm" src="https://cloud.githubusercontent.com/assets/12228435/15375259/fa4717f4-1d02-11e6-9043-2c892af42aab.png">

**Comment by valianttry** [comment]
+1 to @lovegushwa's things.

I left a comment to rework the subject line a while back -- it may have been lost in all the draft back and forth. The subject line does not work, agreed. Some suggestions:
A. One important tip for online security
B. Don't wait. Update! Here's how. (< I worry the exclamation mark might put us into spam filters.... @stephaniemcv I assume you can check if we score high?)
C. Are you undermining your own online security?

I am actually not in love with the email template header design (sorry if I'm doing a 'swoop and poop' here...) -- it doesn't add much in the way of meaning for the recipient, and it actually bumps the text/body WAY down, which isn't great. Can we just remove it? We need to think about the design of our templates so that there is less scrolling, lots of testing shows more scrolling = lower response. In this email in particular our link is waaaaay down.

**Comment by valianttry** [comment]
@stephaniemcv let's add a link a little higher up in the email. Here:
"Trust us: The risk for you is real, so please update your software. " >> link "so please update your software."

Also Steph can you confirm the audience filter and total # or recipients? This should be a test first before we go more widely.

**Comment by mmika** [comment]
+1 C. "Are you undermining your own online security?" 

or maybe 
"Don't undermine your security online." 

we could also go with something short and catchy:
"I updated. Did you?" 
"Out of date." 
"Expired."
"Ready to update?"

@stephaniemcv @valianttry

**Comment by valianttry** [comment]
oooh i like the short and pithy @mmika ... mine were admittedly longer than I'd like. I think "out of date" and "expired" are too clickbait-ey.... Here are options for everyone to vote @HPaulJohnson @mmika @shaghdoosti @natalieworth @lovegushwa @brettgaylor @KevZawacki @stephaniemcv :
A. "Have you updated? It's important"
B. "[first name] -- have you updated?" (<< @stephaniemcv is this personalization possible?
C. "Don't leave your updates waiting"
D. "I updated. Did you?"
E. "Ready to update?"
F. "Don't undermine your security online."

**Comment by KevZawacki** [comment]
My vote: E
Runner up: D

**Comment by stephaniemcv** [comment]
@valianttry 
Subject lines: 
- Exclamation  point is not  throwing any SPAM alerts. As long as we keep it to one, we should be good. 
- First name personalization is not a problem
- +1 on E

Image:
Agreed, I will remove the header and add the new higher link. Actually, I'd like to buttonize this link to break up the brick of text. They seem to be performing well for us.

"Trust us: the risk for you is real."
Button --> Please update your software
@natalieworth what's the hex code of that lovely red/orange from the image?

Audience filter: Anyone in Foundation list (minus known language preference other than EN) that has opened or clicked any of the previous emails in this campaign = ~665,000 HTML.
Text is ~35,000 (unknown behavior)

**Comment by valianttry** [comment]
OK let's go with "E" 
+1 to "buttonize" - NEW JARGON ALERT! 😄 
Let's focus the audience a bit -- people who clicked on an encryption email, since this is a new type of email ask for us.

**Comment by valianttry** [comment]
Since we make software (e.g. Firefox) i worry this layout is now really alarming:

![_test_2_ready_to_update__-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/15412802/8cdf7732-1ddf-11e6-8bc1-e8f9c6bafc68.png)

Could we reduce the size of "The risk for you is real" and the button?

Also, the first source link should drop down a line.

**Comment by stephaniemcv** [comment]
changed to blue to soften too

![button](https://cloud.githubusercontent.com/assets/11812272/15413429/6744345a-1ded-11e6-8aff-77e40ce59e9f.jpg)

**Comment by valianttry** [comment]
Better! I'm R+ (e.g. approved with those changes)

**Comment by KevZawacki** [comment]
@stephaniemcv Email looks really, really great!

One small change from me: Can we put a comma after "update master" in the P.S.? So: 

_P.S. If you want to be a true "update master," go into your software settings..._
