### ISSUE TITLE
Localize optin pop up for Tier 1 languages

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#405]
Detailed description of work: Submit standard optin pop up  to L10n for Tier 1 languages (DE, ES, FR, PL) localization

_Start date: September 19, 2016_ 
_Due date: September 30, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by valianttry** [comment]
Please re open if this is closed in error. Just cleaning up tickets.

**Comment by stephaniemcv** [comment]
Not completed yet.

**Comment by TheoChevalier** [comment]
@stephaniemcv anything needed from me? I’m not sure what is the optin pop up

**Comment by stephaniemcv** [comment]
Hrm...I think it's referring to the opt in on the thank you page. So long ago, my memory is fuzzy.

![donation-step-4](https://cloud.githubusercontent.com/assets/11812272/20902007/49c7f0fe-bad9-11e6-92ae-ce11061984b6.jpg)

**Comment by Matt-Holland** [comment]
I think it also includes this "pop up" box which appears if you try to sign up and do NOT check the box for "I'm ok":

![image](https://cloud.githubusercontent.com/assets/1071298/20932300/2a37bca0-bba2-11e6-84e3-6899802df530.png)

**Comment by Matt-Holland** [comment]
@TheoChevalier or @roseregina can you verify whether those two strings (the "I'm ok with the privacy policy" string and the "please check this box" string) are already present in the Tier 1 languages (DE, ES, FR, PL), and if they are not, add them to the localization plan? And then reply back to this ticket.

**Comment by TheoChevalier** [comment]
Thanks everyone for the clarifications, here’s the status:

“Please check this box if you want to proceed.” is displayed by the browser and not by the website, so it’s definitely translated:
https://transvision.mozfr.org/?sourcelocale=en-US&locale=fr&repo=release&search_type=entities&recherche=dom/chrome/dom/dom.properties:FormValidationCheckboxMissing&perfect_match=perfect_match

For the e-mail opt-in, it’s also translated in every locale we support *BUT*, it’s only enabled for en-US and German.
See the difference here:
German: https://donate.mozilla.org/de/thank-you
French (and any other locale): https://donate.mozilla.org/fr/thank-you

@ScottDowne Assigning this one to you, since I guess we want to enable all locales here? I could do the patch if you point me to the code enabling this opt-in

**Comment by ScottDowne** [comment]
I'll need to confirm when I'm at a computer in a bit, but I'm pretty sure
those errors are default html errors and contained and localized in the
browser itself. You might need to change your browser language to see those
strings change language maybe.

**Comment by ScottDowne** [comment]
So yeah, once I got to my computer I could read this more closely.

I think Theo sums it up well, we need to enable signup for other languages, hence enable the signup page too. Historically, last year we made a decision we only had capacity to engage with English and German effectively. I do have to ask, we are confident we have the capacity to grow our mailing list and engage with them for all languages now?

@TheoChevalier to fix this, basically remove these lines: https://github.com/mozilla/donate.mozilla.org/blob/master/src/pages/thank-you.js#L22-L25 and replace this line https://github.com/mozilla/donate.mozilla.org/blob/master/src/pages/thank-you.js#L34 with `<Signup country={this.props.country} email={this.props.email}/>`

**Comment by roseregina** [comment]
When this happens, is there a way to pre set the sign ups to the correct language in the sales force database? 

If not, let's make sure that there is adequate language/ visuals reminding people to chose a language so that we don't have a heap of people trying to engage with us who we turn right around and alienate with mail in english which they take as a proof that we we don't really care about them.

**Comment by ScottDowne** [comment]
It's auto detected from the URL already.

**Comment by roseregina** [comment]
awesome. that is good to hear. thank you.

**Comment by Matt-Holland** [comment]
Ok, I'm going to close this ticket. Deciding whether/how to expand the mailing list into other languages is out of scope for EOY 2016 fundraising.
