### ISSUE TITLE
Petition V2: Review form V2.5

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#468]
Detailed description of work:
Please review the v2.5 petition here: https://petitionv25-mozillafoundation.nationbuilder.com/.  

Let's log any issues specific to the form in this issue. 

CC: @beccaklam @lovegushwa @brettgaylor @valianttry @HPaulJohnson

**Comment by beccaklam** [comment]
# **First off, the form looks great! So awesome to see the designs come to life 👍 Here are the issues I've found:**

## 1. Thank you text in black, please change to white. Can we also have the string sit on one line for desktop and tablet? This way the band is not as thick.

### No:

![screen shot 2016-09-22 at 2 25 44 pm](https://cloud.githubusercontent.com/assets/20977376/18760784/78c91056-80d0-11e6-8798-f433a7598ca6.png)

### Yes:

![screen shot 2016-09-22 at 2 26 51 pm](https://cloud.githubusercontent.com/assets/20977376/18760788/83626256-80d0-11e6-8c6e-26e12f81253b.png)

## 2. Add some padding below the form, right now the progress bar is sitting a bit too tight to the edge of the browser. I think adding 15px should be enough. Also, can we increase the font-weight of 'Sign The Petition' to 900? The other font-weights for the form fields look fine.

### No:

![screen shot 2016-09-22 at 2 32 29 pm](https://cloud.githubusercontent.com/assets/20977376/18760963/25e2f950-80d1-11e6-8f99-ec3203286f58.png)

### Yes:

![screen shot 2016-09-22 at 2 32 48 pm](https://cloud.githubusercontent.com/assets/20977376/18760968/29a6df70-80d1-11e6-9bfb-f08581c9410d.png)

## 3. Progress bar: After a user is done filling in a step and clicks to the next step, the previous step's name should turn a greyed out pink. See below:

### No:

![screen shot 2016-09-22 at 2 37 57 pm](https://cloud.githubusercontent.com/assets/20977376/18761172/e48f9ee4-80d1-11e6-84e4-1041407d8638.png)

### Yes:

![screen shot 2016-09-22 at 2 39 13 pm](https://cloud.githubusercontent.com/assets/20977376/18761188/f5c46096-80d1-11e6-8ac0-1a96143c107a.png)

## 4. Country form field/Mobile form fields breaking, height does not match button height:

![screen shot 2016-09-22 at 2 40 04 pm](https://cloud.githubusercontent.com/assets/20977376/18761235/1fbe514a-80d2-11e6-9f55-9dfc1703a222.png)

## This seems to happen for all form fields when I test the form on my mobile

![img_6447](https://cloud.githubusercontent.com/assets/20977376/18761531/5b0d4aa2-80d3-11e6-8f36-352d9145958a.PNG)

## 5. Weird loop on mobile when swiping through carousel, it seems to reset after you type into a form field. Is there a way to get the swipes to 'snap' to each step so we don't get this bug?

![img_6445](https://cloud.githubusercontent.com/assets/20977376/18761623/a9aba05a-80d3-11e6-9439-81fe57b06512.PNG)

## 6. Can we make the carousel buttons actually work? Right now they don't respond to mouse clicks or taps on mobile.

## 7. After signing on mobile I get this screen instead of the thank you bar for signing:

![screen shot 2016-09-22 at 2 53 52 pm](https://cloud.githubusercontent.com/assets/20977376/18761771/4ae264f4-80d4-11e6-98f8-78bdb029bbcd.png)

### When I click into it I then get the thank you bar:

![screen shot 2016-09-22 at 2 54 07 pm](https://cloud.githubusercontent.com/assets/20977376/18761781/525689cc-80d4-11e6-8c8c-ef40b64abfdd.png)

### Is there a way to just get it to go immediately to the thank you bar instead?

## 8. Mobile Button Styling: Can we decrease the margins around the pink button to 10px, increase font-weight to 700 and increase font-size to 1.3em?

### Current:

![screen shot 2016-09-22 at 2 57 15 pm](https://cloud.githubusercontent.com/assets/20977376/18762054/4ec531f4-80d5-11e6-83d3-60cf9c7ad712.png)

### Change to:

![screen shot 2016-09-22 at 3 01 19 pm](https://cloud.githubusercontent.com/assets/20977376/18762063/56871d08-80d5-11e6-9d4f-2673a200235e.png)

## 9. When signing the petition I can fill a form and hit enter and proceed to the next step (which is AWESOME) but I then have to use my mouse and then click into the new form field. Is there a way where after hitting enter on the previous step, the next step slides in with the user's cursor already in the form field? It's a but disruptive to have to stop typing and use my mouse.

## 10. Can we change the text-nav to align left? Currently it is centering and looks awkward.

### Current:

![screen shot 2016-09-22 at 3 07 44 pm](https://cloud.githubusercontent.com/assets/20977376/18762271/0a3221ae-80d6-11e6-80c5-523601d7cb5a.png)

### Change to:

![screen shot 2016-09-22 at 3 07 57 pm](https://cloud.githubusercontent.com/assets/20977376/18762275/0ebb6316-80d6-11e6-8b45-99ed1fc8ccc5.png)

**Comment by damiankay** [comment]
@beccaklam - can you identify which of these are vital for launch and should be addressed first? There are a lot of issues that you've identified here. Thanks!

**Comment by beccaklam** [comment]
@damiankay I would say P1s would be 1, 4,5,7 and 10
The rest are really easy style changes though that should be quick. 
CC: @lovegushwa

**Comment by valianttry** [comment]
@lovegushwa can you close this if these have been addressed? I think you said on a call today these were all gtg.
