### ISSUE TITLE
Maker Party: SF field mappings

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#477]
Moving this thread to Github from email. 

@drewmoto suggested the field map in the image below. 

@jendc123 flagged that this will take 5-7 hours to implement

Is there another option that is a lighter lift? I don't know enough about this to make a decision. Can @drewmoto weigh in please? 

CC: @valianttry @stephaniemcv @imagerwalt

![sf-field-map](https://cloud.githubusercontent.com/assets/19785709/18766659/2996157e-80d0-11e6-98bb-b114bf29966f.png)

**Comment by drewmoto** [comment]
We can assign these Campaigns to the Parent Campaign later next week if we need to if the code changes interfere with our schedule. I can utilize the data loader API tool we have. It is not a blocker to go live as long as we are able to create the individual campaigns and assign the hosts and attendees accordingly.

**Comment by damiankay** [comment]
That's great @drewmoto ! Should we move to production then, so that we don't need to worry about that later? I'm assuming we're still in the sandbox.

**Comment by drewmoto** [comment]
Yes. We can push as long as the above conditions are met. Thanks all!!

**Comment by damiankay** [comment]
@imagerwalt any issues with pushing to production? Does this happen on Fission or Mozilla's end?

**Comment by imagerwalt** [comment]
@damiankay The actual update should be much lower than 5-7 hours, but I think it's probably a good idea to allocate some hours for additional testing and potential debugging, just in case.

I can move that to production once we make the update and test it.

**Comment by damiankay** [comment]
@imagerwalt - I'd recommend that we move to production first, and add make the other changes later. @drewmoto is away tomorrow, so we'll have no way of confirming data pass-through on our end. 

Again, not my area, so feel free correct me!

**Comment by imagerwalt** [comment]
@damiankay  I will be able to do both tomorrow, I don't think updating the new parent thing alone really is going to take much time, and doing that probably means we will use less time overall (from the 5-7 hours) as we don't have to go back and correct the data that has been imported.

This is a different process than the user petition sign up (that happened in real time), as this event sync is not happening in real time, it doesn't really matter when the sync actually starts as it will retroactively add those records into SF, including all those before we flip the switch. (That's why I think we need to clean all those test data first before I move it to prod, as all those test events will be recorded in SF otherwise)

But then, the less data we have to track and worry about correct them retroactively later the better.

**Comment by damiankay** [comment]
@drewmoto is there time to delete the test data today?

**Comment by imagerwalt** [comment]
@damiankay Actually, it's those test data from Nationbuilder end that we have to remove. Those in sandbox we don't have to worry about them.

**Comment by damiankay** [comment]
Ok - great!

**Comment by imagerwalt** [comment]
I can delete all those test events once I have them tested with the new parent. So we're good on moving it to prod tmr?

**Comment by damiankay** [comment]
Yes please - thanks!

**Comment by imagerwalt** [comment]
Hey @damiankay I added the parent event to the code. Seems to be working. But I haven't move that to prod yet. Because I am waiting for the the email opt-in part at the moment. George is figuring out the front-end side on setting the email opt in checkbox. So I'm waiting for him on that.

Do you think we can wait till Monday for the push to production? The records will still be added retroactively so unless you really need the records on SF today, I think it's better to push that to Monday.

**Comment by damiankay** [comment]
Yes, Monday is fine. Thanks @imagerwalt !

**Comment by drewmoto** [comment]
Hi All. Looks like the Parent Campaign logic is working so far. Screen shot attached. @imagerwalt @damiankay. Let me know when we can start to expect to do some testing on a few records in Prod and a link I can use to add a few records myself. Thx. 

<img width="1328" alt="screen shot 2016-09-25 at 10 18 24 pm" src="https://cloud.githubusercontent.com/assets/16161696/18823347/ec92615a-836d-11e6-92eb-6a61c0366978.png">

**Comment by damiankay** [comment]
Hi @drewmoto - I'd love to start testing today. Does this just consist of creating some accounts and events through the front-end interface?

**Comment by drewmoto** [comment]
@imagerwalt @valianttry @stephaniemcv 

Hi All - With Damian now out, I want to make sure we/I have eyes on the specific go-live date and time. (I believe it is tomorrow). We also need to send through a few test records to Prod prior to us releasing it out into the wild. Is there a live link I can enter a few records and test a few use cases? Do we want the larger audience to do testing as well? @imagerwalt - Are we pointed to Prod now? And if not now, when? Thx.

**Comment by imagerwalt** [comment]
Hey @drewmoto , I'm currently deleting all the test events on Nationbuilder side, right after that I'm setting the credentials to Prod. should be done in two hours, will let you know when it is finished.

**Comment by imagerwalt** [comment]
Hey @drewmoto I've deleted most of the test ones. There are still a few left, but just want to run by you just in case. (see the attached image)

There're a bunch with the emails like mp.trusted.host@gmail.com or mp.volunteer.manager@gmail.com those I believe are test events as well.

Anyway I'm moving the credential from sandbox to prod now, will let you know when it is tested and deployed
. 
![screen shot 2016-09-28 at 11 13 34 am](https://cloud.githubusercontent.com/assets/283657/18926462/c2ce43ba-856c-11e6-9b3b-8b73d7141d75.png)

**Comment by imagerwalt** [comment]
Hey @drewmoto I set the credential to prod now, you should see the events popping up in the prod one now. 

There will be a bit of clean up after this (need to merge the files as now I keep two separate copies since we are using one single heroku repo for both sandbox and prod). 

But before I do that, George just mentioned in the other issue thread here (https://github.com/MozillaFoundation/Advocacy/issues/475#issuecomment-250258729) that the email opt in on the front-end is set, I am going to link that as well in the back-end sync to SF. Will do that after lunch.

**Comment by drewmoto** [comment]
One last one @imagerwalt. I dont think we are mapping to a field in SF for "Send Me Text Messages". Was this discussed on another thread? Do we need to map this, or is NB taking care of the texting part? cc @stephaniemcv @valianttry 

<img width="1057" alt="screen shot 2016-09-28 at 1 03 45 pm" src="https://cloud.githubusercontent.com/assets/16161696/18930263/36d16940-857c-11e6-8577-13c47adb0a55.png">

**Comment by imagerwalt** [comment]
Hey @drewmoto , I'm looking into it now. I also noticed the creator is not sync'ed correctly, as it should. (under CampaignMembers).

**Comment by imagerwalt** [comment]
Hey @drewmoto , fixed some bugs so creator is now synced, I'm misread your message earlier, I thought you wanted to add the SMS option to SF but I guess what you were saying is if SMS is needed? Is that correct?

If you want to remove that option, I'll let George know about it so he can remove that from the option.

**Comment by drewmoto** [comment]
Hi Andrea and Steph.

Do we need to track the SMS option in Salesforce/NB?

**Comment by valianttry** [comment]
I need to check with @shaghdoosti . I would be surprised if we wanted to include SMS / phone fields anywhere on our sites. Hang tight I'll ask.

**Comment by valianttry** [comment]
We don't have an SMS program, correct? Why would we collect phone?

![maker_party_cluj](https://cloud.githubusercontent.com/assets/9830371/18939276/ebd0fda6-85b3-11e6-8496-5b1d8ed7874b.png)

**Comment by stephaniemcv** [comment]
No SMS program that I'm aware of.

**Comment by imagerwalt** [comment]
Okay, I mentioned that to George, he should be able to remove that option tomorrow. As far as the email opt in it is showing up in SF now. But I have one issue I still don't quite know what exactly happened, the "Open Innovation Bonanza" one keeps having duplicates (and not the others).

I do have a query to check if an event with the same name exists, but maybe it's not good enough for some reason (and potential error with foreign language with accented characters (I think it is unicode, but just in case)). @drewmoto do you think you can add a new field to "campaign" object, something like "Nationbuilder_id__c" so we can tag a ID there to match the event instead of doing a name search.

If that's not possible, I can probably add the SF ID into Nationbuilder, but that will be more work, as I will have to save the data back into NB after the sync.

**Comment by drewmoto** [comment]
Hi Walter,

I added the field in Prod and Dev.

And to add a comment, if it is a better process and is more scalable to add
the ID in NB, lets do that. I know we are in a time crunch but I dont want
to have to go back and reconfig this at a later time if possible.
Conversely, if we are just doing this as a temporary solution, thats fine
as well, I just need to know the remediation plan.

Thanks,

**Comment by imagerwalt** [comment]
Thanks Andrew!

Yeah agreed, adding the SF id to NB shouldn't be a problem. Also, as soon as the Maker Party stuff is done, I'd like to go back to the petition to test the new code I rewrote - the first version the code was kinda messy as we had to do patch a lot of stuff in less than 3-4 days, I reorganized the code a bit but I haven't tested it yet.

I also have to merge the two salesforce api backend code files (the one for petition and another one for Maker Party) Had to have them separated because we are currently using a single Heroku instance for both Sandbox and Production Salesforce, so just in case I didn't want to change anything in the existing one at the moment.

Oh can we create a separate Heroku instance for staging, the single heroku approach is kinda dangerous...

Thanks,
Walt

**Comment by jendc123** [comment]
@drewmoto @valianttry - we have removed the text SMS from the front-end.  In order to move forward with the rest of the ticket, @imagerwalt needs access to SF to track the nationbuilder ID.

**Comment by drewmoto** [comment]
I created the field in both Dev and Prod. Walter should be able to test in
Dev at this time. I didn't revoke access to that.

**Comment by imagerwalt** [comment]
Hey @drewmoto I think my access "walter7@fissionstrategy.com" to the whole SF is disabled, as I can't even log in via na.48.salesforce.com right now.

**Comment by drewmoto** [comment]
Looking into now

**Comment by drewmoto** [comment]
- The BSD Sandbox server is cs26 (see below)
  - https://cs26.salesforce.com/home/home.jsp
- Direct login access is test.salesforce.com
  - Your username should still be walter7@fissionstrategy.com

Screen shot attached of your (active) Sandbox account. If that doesnt work
let me know.

**Comment by drewmoto** [comment]
na48 is the Production location.

And you had a decimal in your server na.48 as opposed to na48. Was that
intentional?

**Comment by imagerwalt** [comment]
Oh it was an typo. oh okay, sorry I misunderstood your message. Yeah I'll update it from cs26 sandbox now.
