### ISSUE TITLE
https://makerparty.community is an untrusted connection

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#490]
Detailed description of work: We need to ask NationBuilder to redirect https://makerparty.community to https://www.makerparty.community

Let me know if this is incorrect @cadecairos 

_Start date: September 23, 2016_ 
_Due date: October 5, 2016_

Guessing on these start dates, we can move it around. 

CC: @damiankay

**Comment by cadecairos** [comment]
It is correct. Right now they're only redirecting on port 80 ( http://makerparty.community )

**Comment by damiankay** [comment]
@cadecairos or @ScottDowne can you please submit a support ticket, and CC me on the initial email response? I'll escalate it right away, but Dana is traveling, so best to get it directly in to their support team. 

Thanks! 

CC @valianttry

**Comment by valianttry** [comment]
@cadecairos or @ScottDowne did that support email yield any results?

**Comment by ScottDowne** [comment]
@valianttry Nope, I didn't but I was kinda hoping @cadecairos was in a better position for this, with knowledge and experience around this and the history.

@cadecairos any chance you already request this? Is it somehow different this time around than for changecopyright.org? I'm actually confused as too why this is even a thing given we already solved this once.

**Comment by cadecairos** [comment]
Last I heard of this ticket was that Damian was going to ask Fission/Nation Builder

Who is our contact at NB that I can ask about technical things like this?

**Comment by cadecairos** [comment]
> can you please submit a support ticket,

oh, totally didn't see this until now.

**Comment by cadecairos** [comment]
Support request filed.

**Comment by cadecairos** [comment]
So, NationBuilder isn't able to redirect the apex domain using https.

Here's my plan to solve this.
- [x] 1. Get an ssl cert for makerparty.community
- [x] 2. set up a cloudfront CDN to handle http and https connections to `makerparty.community`, use an s3 bucket redirect rule to redirect connections to `www.makerparty.community`
- [x] 3. Create a new hosted zone in AWS, alias the apex to the cdn, cname the `www` subdomain to `www.changecopyright.org.edgekey.net` (which seems weird, will confirm this does what they claim it will)
- [ ] 4. ask Webops to update the nameservers for makerparty.community so that it uses the new hosted zone I set up in step 3
- [ ] 5. Update Domain configuration in NationBuilder
- [ ] 6. make some parties!

@HPaulJohnson my best estimate of the time required to complete the above tasks, without ringing _all_ the alarm bells, is 1-2 days. Is that okay? If we need it faster, I can probably make it happen in the next 12 hours (be aware that changing nameservers for a domain still can take 24 hours to spread around the world)

cc/ @valianttry @shaghdoosti

**Comment by HPaulJohnson** [comment]
thanks for flagging me @cadecairos - i defer to @valianttry and @shaghdoosti on the question about timing.

**Comment by valianttry** [comment]
Just talked with @shaghdoosti -- we will set launch to Thursday 12 noon PST to provide enough room / time to make certain this is fixed.

**Comment by cadecairos** [comment]
Thanks, I'll kick off 1, 2 and 3 very shortly

**Comment by cadecairos** [comment]
I've got an SSL cert, A Cloudfront domain, an s3 website to redirect, and a new hosted zone ready to be enabled. Seeing as how I've got 10 minutes left in my day, I'm going to pick this up tomorrow morning. If I didn't mess anything up, we'll be ready to launch (Domain/SSL-wise) Wednesday morning (to allow for DNS changes to propagate worldwide)

**Comment by cadecairos** [comment]
Filed the bug to take back management of DNS on makerparty.community: https://bugzilla.mozilla.org/show_bug.cgi?id=1307410

I'll update the domain in NationBuilder when that bug is closed.

**Comment by cadecairos** [comment]
All looks good, DNS seems to have updated in most if not all places, and the apex domain now redirects using SSL.
