### ISSUE TITLE
NEW snippet design in Activity Stream. Foundation feedback and questions

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#496]
Detailed description of work:
The current snippet is going to eventually make way for an activity stream version. Here are detailed mockups of what they would look like, including a fundraising snippet:

https://mozilla.invisionapp.com/share/DX8O1JFMA#/screens/187604366 

@vojtechmzl and @ScottDowne and @lovegushwa and @HPaulJohnson  let's use this ticket to record feedback and questions. I will then take them all to the IPC team on our behalf.

_Start date: September 23, 2016_ 
_Due date: September 27, 2016_ 

CC:

**Comment by valianttry** [comment]
For fundraising: How easy will it be to test design elements and text? For instance, 2 amount buttons vs. 4? Different sentences hotlinked? 

![new_tab-snippets](https://cloud.githubusercontent.com/assets/9830371/18797062/e3e4e0ee-8180-11e6-88ec-629c9b010faa.png)

**Comment by ScottDowne** [comment]
Just some of my thoughts.

Possibility of takeovers? Or are spectacular snippets pretty much off the table? We could have something that covers the whole page, and when you x or otherwise interact with it, it goes away? Similar to the mozilla.org takeover we do.

Is that fundraising snippet an example or a proposed template?

I like that the x button is being cleaned up a lot. It's much better in this doc.

Glad we have buttons, and a snippet still!

Page is much busier now, and looks like it'll have vertical scrollbars at times.

Snippet at the bottom of the page might be bad for us.

One of the things I liked about the previous page was how simple it was.

All for now.

**Comment by lovegushwa** [comment]
I agree with @ScottDowne
- We should also push for adding color to the snippet background / as kind of a mini spectacular snippet.
- We should find out if we can leverage animation to help us compete for eyeballs, lots of other content we need to compete with.

**Comment by valianttry** [comment]
I shared this ticket with Jean Collings -- she needed our feedback earlier this week. Closing this ticket.
