### ISSUE TITLE
Maker Party: Add link to Nationbuilder Privacy Policy

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#513]
Detailed description of work: 
Hi @gholme4 @barfaaa - can you please add a link to the Nationbuilder privacy policy to the [sign in page](https://makerevents-mozillafoundation.nationbuilder.com/forms/user_sessions/new). 

Above the "Activate Account" button, could you add: "By proceeding, you agree to Mozilla’s Terms of Use and Privacy Policy as well as NationBuilder’s 3dna Privacy Policy."

Above the "Attend" button on the RSVP form, add: "I'm okay with you handling my information as explained in the Mozilla Privacy Policy and NationBuilder’s 3dna Privacy Policy."

These should link to: http://nationbuilder.com/privacy

_Start date: September 26, 2016_ 
_Due date: September 27, 2016_ 

CC: @jendc123 @valianttry

**Comment by gholme4** [comment]
@valianttry #readyforreview

**Comment by valianttry** [comment]
@gholme4 not sure this is the right ticket, but this looks correct except the URL for "Mozilla's Terms of Use" shouldn't have "en-US" locale. So instead of https://www.mozilla.org/en-US/about/legal/terms/mozilla/ It should be:

https://www.mozilla.org/about/legal/terms/mozilla/

![activate_your_account](https://cloud.githubusercontent.com/assets/9830371/18897743/b0e9617e-84e1-11e6-928a-d08660d34691.png)

**Comment by gholme4** [comment]
@valianttry I made that change to the terms links. #readyforreview
