### ISSUE TITLE
Adding Sticker Order Link to Website

### ISSUE THREAD

**Issue by LucyeoH-zz** [MozillaFoundation/Advocacy#564]
- Does it need to be localized?
  - Yes
- Does it require a developer?
  - Yes
- Who is the real audience?
  - Hosts 

Detailed description of work:
@kelimuttu @couci have created a process for ordering stickers for Maker Party. https://github.com/mozilla/reps-regional/issues/64

The link is ready to go [here](https://docs.google.com/a/mozilla.com/forms/d/14zPnrNun7TUmMySx7t7ugbNCSbNl9dhK7O5oYqUL8Y0/viewform?edit_requested=true) and they would like it to appear on the website as well as in the host pack. 

Can we add it under "Logos & Assets" - https://learning.mozilla.org/en-US/events/resources

_Start date: Oct 5, 2016_ 
_Due date: Oct 8, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by ScottDowne** [comment]
@lovegushwa or @beccaklam thoughts around design?

Regarding localization, it's possible having a single english form for all languages isn't that bad, but if it is, we can enable it for just English, or localize the form.

@LucyeoH Thoughts?

**Comment by LucyeoH-zz** [comment]
I think that the vast majority of our EU hosts are going to be okay submitting the form in English but if for consistency it needs to be translated we're okay with the related delay.

**Comment by beccaklam** [comment]
@ScottDowne @LucyeoH What feedback do you need around design? Do you mean design of the form or how we would add the sticker order link? Also, what do the stickers look like? Are they like the buttons?
<img width="213" alt="screen shot 2016-10-12 at 4 47 32 pm" src="https://cloud.githubusercontent.com/assets/20977376/19327043/2717cf06-909b-11e6-97d3-030de6f7cf87.png">
cc: @lovegushwa

**Comment by ScottDowne** [comment]
Yeah, I need to know where to add the button and what it should look like. If it should even be a button? Looks like the form itself is done.

This sounds really open ended, actually. It sounds like the real issue is "we have this form, and we need to put it somewhere. The events page seems pretty good?" So one thing I think we should challenge is if the events page actually the best place for this. Is it the only place for it? I would agree that the events page seems logical, but I still want to challenge it, because putting it there causes l10n issues.

Logos & Assets seems to have a specific usage, so I want to be sure we're not tack it onto something without thinking it through.

**Comment by ScottDowne** [comment]
I'm thinking a separate section for sticker order on https://learning.mozilla.org/en-US/events/resources a link or button, that takes you to the order form makes the most sense. For now it would only be visible in en-US. We can then see how many people use it, and how many request it to be localized.

As I get localized forms, I can enable it for more languages.

**Comment by LucyeoH-zz** [comment]
Copy for this: 

Planning a Maker Party in the EU? Order stickers for your event here.

**Comment by ScottDowne** [comment]
@LucyeoH test branch here: https://learning-mozilla-org-s-pr-2341.herokuapp.com/en-US/events/resources

Waiting on review.
