### ISSUE TITLE
[MozFest] Meme designs for buttons

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/Advocacy#574]
**Detailed description of work:**
We are providing a space for participants to make buttons/pins at MozFest. Since our copyright campaign incorporates memes, we'd like to provide meme-based designs for our participants to create their own buttons. Example ideas:
- Black/white outlines of popular memes like doge, philosraptor, etc so that people can color them 
- Full color memes with phrases like "save me" or "I'm not illegal" across them
- Creative Commons licenses (maybe a little boring)

We will be purchasing [this button maker](https://www.amazon.com/Badge---Minit-Machine-Starter-designs/dp/B012O1JJP4) from Amazon. Specs say the buttons/images are 2.25 inches in diameter.

What we need:
- About 5 - 10 different designs that participants can customize or use as-is
- Designs that fit within a 2.25" diameter circle
- Button designs laid out to be printed on A4 paper

I'm setting the date for Oct. 20, but sooner the better. I will be sending these designs to a printer in London so that they're ready for MozFest.
_Start date: October 6, 2016_ 
_Due date: October 20, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @lovegushwa

**Comment by brettgaylor** [comment]
I feel like we've bought a button maker before...I think it was left somewhere cuz its heavy and expensive to ship?

**Comment by chrislarry33** [comment]
We have one in Brooklyn Office, should we ship/bring to MozFest?

**Comment by Melechuga** [comment]
@chrislarry33 Oh nice! Yea, if it's not too much of a hassle. What size is it (the diameter of the button)? The one I was going to get is a hand-push button maker and is pretty small/light. Button diameter is 2.25"

**Comment by Melechuga** [comment]
@beccaklam Thank you! I found an example with the Jean Luc Picard facepalm: 
![](https://img1.etsystatic.com/111/0/12086792/il_214x170.1057660261_o4us.jpg)

Can we do this with doge and other memes?

**Comment by beccaklam** [comment]
@Melechuga Yup!

**Comment by beccaklam** [comment]
Hi @Melechuga  Before these get started can you okay this list of memes? Just want to make sure these are the kinds of memes you were hoping for. Most of them are pulled from the meme-jail video: https://docs.google.com/a/mozilla.com/document/d/1H5HK7af8XxatmSsHW-aYWCFqPpEGoWGTRl8XCxjETTM/edit?usp=sharing

CC: @lovegushwa @natalieworth

**Comment by Melechuga** [comment]
Hey @beccaklam Thanks for making a list! We're going to have grumpy cat masks, so maybe we don't need the pins. I know the Arthur (fist) meme, but is there a way we can do something more positive/less aggressive? How about 2 of the 3 below:
[Success kid](http://static2.businessinsider.com/image/56e3189152bcd0320c8b5cf7-480/sammy-griner-success-kid-meme.jpg)
[Queen of England](http://cdn.images.express.co.uk/img/dynamic/galleries/x701/127176.jpg)
[Sound of Music](http://www.troll.me/images2/sound-of-music/sound-of-music.jpg)

**Comment by beccaklam** [comment]
Hi @Melechuga here is the redpen with the buttons so far. I'm also hoping to make some more typography-driven ones :) https://redpen.io/p/hea17c8fb9339419fe
I also printed the buttons out and the size seems good enough (the queen and success kid are a bit small but still colour-able):
![img_6526](https://cloud.githubusercontent.com/assets/20977376/19357774/0a200e58-9141-11e6-80dd-c617f7908c80.JPG)
P.S. Grumpy cat is there because I had already drawn her before you told me not to! I think people love Grumpy cat so having her in two activities is not a bad thing :)

CC: @lovegushwa

**Comment by Melechuga** [comment]
Hahaha AWESOME!! No worries about Grumpy Cat; it's perfect. You totally have creative license with this; feel free to do whatever you think is best and fun. Thanks!

**Comment by beccaklam** [comment]
Link to printable pdf on A4 paper: https://drive.google.com/open?id=0BzuBOR2VJQqUcFNTcWZzNG5ueVE (Grumpy Cat and Doge are repeated... we can fit 12 buttons on an A4 sized sheet of paper and since there are 5 buttons only 2 can repeat 3 times, I guessed that those may be our two most popular but @Melechuga if you have another hunch let me know!)
