### ISSUE TITLE
Discussion: Should we test cloning a single petition page for each locale to improve page load time?

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#585]
Detailed description of work:
Page load times are killing conversion and costing us $$. Bablic seems to be the primary culprit. Can we clone a separate petition for each language to speed up load time?

I suggest we test this theory with German, and gauge the work / reward.

CC: @jendc123 @gholme4 @HPaulJohnson

**Comment by jendc123** [comment]
Hi @valianttry - We can get a working site up in 3-4 hours so it would not be a heavy lift on our end.  Would we hold data in Nationbuilder or would it need to be passed through to Salesforce?

**Comment by valianttry** [comment]
@jendc123 for the test I think it's fine to hold the data in NB as long as we can push it through eventually. But yes I think ultimately we would want the data to pass through to SF if we decide to move forward and build individual page per locale. The test probably doesn't need to run that long depending on traffic. (cc: @vojtechmzl so he can weigh in on any other implications for this test).

Also, can you help us understand how localization would work? Can you pull all the localized strings into a cloned German petition? I just want to understand if we have to redo all strings; etc.

**Comment by jendc123** [comment]
@valianttry - the mock-up was in German [https://redpen.io/bh9e2c7a6d82f9f458] so for this one we wouldn't have to worry about translations. If we were to convert other languages we will have to brainstorm on the best way forward.

**Comment by valianttry** [comment]
ok -- just note that we may have made minor updates in Bablic to the German since that mockup was made. We should definitely QA to make certain it's all correct before launching.

**Comment by brettgaylor** [comment]
Hello!

German may not actually be the best market for this test, as we've been running there already and are starting to see content fatigue.  We'd probably want to use a market that we haven't run in yet, such as Spanish - @HPaulJohnson could say for sure.

Even within that mockup there are lots of subtle places where english is used - with all of the shuffle, do we have a master source of truth for all of the strings on a given page?

**Comment by valianttry** [comment]
cc @TheoChevalier

**Comment by vojtechsedlak** [comment]
From testing perspective, all we would need is two URLs to split the target traffic in between, which can be set up through Optimizely. Would the domain of the test version change from changecopyright.org or would it live on its subdomain?

**Comment by brettgaylor** [comment]
Do we need to actually test this?  Wouldn't we immediately know the page load time?

**Comment by HPaulJohnson** [comment]
+1 one to the idea of testing this which shouldn't be hard with 2 URL's. We'd be able to quantify impact of speed on conversion which should help inform future tech discussions/decisions.

**Comment by brettgaylor** [comment]
Got it!  I stand corrected.  @HPaulJohnson which locale do you think we should perform this test with?

**Comment by HPaulJohnson** [comment]
@brettgaylor I like the idea of doing it with a fresh audience too, so Spanish would be great given we already content localized for that.

**Comment by HPaulJohnson** [comment]
what's the next step here? are we good to proceed with building out a single page to test this approach?

cc: @brettgaylor @valianttry

**Comment by brettgaylor** [comment]
@TheoChevalier and I will discuss with Fission and report back

**Comment by ScottDowne** [comment]
Just flagging something here that might not be addressed, or simply making sure we're aware of the issue around maintaining multiple copies of a page per locale. It's reasonable for 1/2 locales in a test, but that just allows us to run a test to confirm our theory as to what the issue is.

It however does not validate a reasonable solution. The more the page becomes forked, the more work we need to do to make updates. Think trying to run in cement shoes. It also opens up the floodgates to QA and bug headaches, you now need to test every page in every locale for every feature after every change. If you have 5 locales, QA at the same level may be 5 times longer. 5 locales is a tiny amount. We have 9. This is hard even at a small scale.

You may be thinking the increased maintenance and QA cost out weighs the hits we are losing from the load time. I hope this is the case, but we can also miss something critical now in the QA process, do unexpected amounts of damage, and not be able to move quickly to fix it.

This is how l10n worked two years ago for donate, I know from experience, and a lot of bugs, that it's a huge cost. This was one of the reasons we moved away from BSD.

I'm hoping this has been address, or nationbuilder has a way to manage this, or we have accepted these costs? (as this is the primary thing bablic offers, removing it, removes that feature, and if nationbuilder supported this, bablic wouldn't have a market).

Does this make sense?

**Comment by brettgaylor** [comment]
Yes, totally makes sense - though keep in mind that we are only considering this for certain markets where we will roll out paid media.  We won't do all 8 locales this way.

We will also keep the same functionality for users on changecopyright.org that allows them to use bablic to change their locale.

To answer your question: yes, we feel that the real cost to do this is worth it given the cost penalty we are incurring in our paid media because of the page load times.

It is not something to repeat again, and should definitely inform our thoughts on nation builder as a platform.

**Comment by TheoChevalier** [comment]
@jendc123 Hey Jennifer, we just found those issues with the static page. Fixing them should be pretty straightforward, but we should really fix them before launch.

In the form, some strings are French translations:
Confidentialité > Privacidad
Affichez votre soutien > Muestra tu apoyo

In the footer:
Galletas > Cookies 
(It should should be kept as-is in Spanish)
It would be interesting to understand where you got this translation from, in order to fix the issue upstream.

Let us know if you have questions :)

**Comment by ScottDowne** [comment]
@brettgaylor great response. Pretty much exactly what I wanted to hear :D :rocket: :guitar:
