### ISSUE TITLE
Does Stripe have new features we should try to implement for EOY 2016?

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#592]
Detailed description of work:
Are there new locales, currencies, or features Stripe is offering that we should implement? 

_Start date: October 17, 2016_ 
_Due date: October 25, 2016_

**Comment by valianttry** [comment]
cc @cadecairos

**Comment by ScottDowne** [comment]
### ACH

Seems ACH payments is still the top of the "new" payment processors. We've known about this one for a while now, but it's worth mentioning again. It doesn't solve our German needs, as it's US only. https://stripe.com/docs/ach

### Bitcoin

They have a way to process bitcoin. I doubt it's worth us migrating what we have as it already works and is simple enough from what I can see, but might be worth mentioning because I wasn't aware they supported bitcoin. https://stripe.com/docs/bitcoin I could come up with some pros and cons, but I doubt we have much to gain here.

### Currencies

Stripe still has a silly number of currencies: https://support.stripe.com/questions/which-currencies-does-stripe-support#currencygroup1

Paypal is still the bottleneck here: https://developer.paypal.com/docs/classic/api/currency_codes/#multi-currency-support-for-paypal-payments

I'm moving the stripe/paypal currency support conversation to here: https://github.com/MozillaFoundation/Advocacy/issues/374

### Radar

Also @cadecairos has been pointing out in chat, Stripe has upped their fraud game with radar https://stripe.com/radar

We're already using it.

I also found this to be an interesting read https://stripe.com/radar/guide

**Comment by roseregina** [comment]
This comment (#14578) from a donor seems potentially relevant for the bitcoin discussion, though I suspect that stripe is still more complicated than the donor would like: 

> I tried to donate with bitcoin. It's far too complicated. Why am I 
> redirected to coinbase? Why do I need an account? It should be simple. 
> Where's the QR code?

**Comment by ScottDowne** [comment]
I'm pretty sure anything bitcoin related can be tackled (if at all) in 2017.

**Comment by ScottDowne** [comment]
Radar and new currencies were done, the rest I think isn't happening this year.

We can file a specific ticket for ACH or coinbase things if we expect to use it this campaign.
