### ISSUE TITLE
QA for Spanish-only petition

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#604]

**Comment by TheoChevalier** [comment]
(Reposting here as it’s more appropriate)
@jendc123 Hey Jennifer, we just found those issues with the static page. Fixing them should be pretty straightforward, but we should really fix them before launch.

In the form, some strings are French translations:
Confidentialité > Privacidad
Affichez votre soutien > Muestra tu apoyo

In the footer:
Galletas > Cookies
(It should should be kept as-is in Spanish)
It would be interesting to understand where you got this translation from, in order to fix the issue upstream.

Let us know if you have questions :)

**Comment by brettgaylor** [comment]
Disregard earlier comment about footer links - Théo tells me they are as they should be, and allow the browser to set the appropriate locale.

**Comment by TheoChevalier** [comment]
@jendc123 Changes to the form look good, but there is still an issue in the footer, it needs to be “Cookies”, not “Galletas”. Once this is fixed, we can close this ticket.
Thanks!

**Comment by jendc123** [comment]
Hi @TheoChevalier - sorry about that it's been updated.

**Comment by TheoChevalier** [comment]
Looks good, thanks!

**Comment by jendc123** [comment]
Hi @brettgaylor and @TheoChevalier - this is now live [https://es-mozillafoundation.nationbuilder.com]

**Comment by brettgaylor** [comment]
🎉
