### ISSUE TITLE
EOY Test Idea: Culturally-specific Snippet Copy

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#629]
Detailed description of work: We haven't done much testing for snippet copy outside of en-US, so let's see if we can brainstorm ideas for culturally-specific snippets for the following locales:

en-gb
de
fr
es
pl

The hypothesis here is that tailoring the copy of the snippet to the target audience (e.g. by mentioning EU copyright in the EU snippet) will increase click-through rates over generic/universal copy.

@TheoChevalier, can I schedule a quick call where we can brainstorm some ideas around this?

*Start date: November 14, 2016* 
*Due date: November 23, 2016* 

CC: @valianttry

**Comment by TheoChevalier** [comment]
@vojtechmzl Yeah sure, anytime tomorrow would work for me

**Comment by vojtechsedlak** [comment]
Moving ahead with this. Theo is reaching out to localizers in the target communities to gather feedback and ideas for culturally-specific snippet copy and images. We hope to hear back by early next week, giving us time to set the test up before the end of next week.

**Comment by vojtechsedlak** [comment]
Hey @TheoChevalier, I found the [document with draft snippet copy](https://docs.google.com/document/d/1Wq6_iDGpd2XC426N96357QE_4N6P5F3W5p83Dql5UGQ/edit?ts=58236f11) for this year's EOY campaign. I am not sure if this is final and approved, but hopefully it can be useful for in coming up with locale-specific tweaks. Thanks!

**Comment by vojtechsedlak** [comment]
Hey @TheoChevalier, did we end up hearing back from any other community members last week? We are going ahead with testing localized icons, so we can close this ticket, unless any new ideas emerged. Thanks!

**Comment by TheoChevalier** [comment]
@vojtechmzl unfortunately no :/ I have this alternative copy for French, https://public.etherpad-mozilla.org/p/eoy-custom-snippets-fr but I’m not convinced it’s better than the current one. (I’ve added a literal translation at the bottom). If you want to test it, go ahead, but otherwise, let’s close the ticket.

**Comment by vojtechsedlak** [comment]
This is great. There is a separate effort to get a bunch of copy variants into the approval pipeline this week, so let's add this there. I think it's worth testing. Thanks for your help!

**Comment by HPaulJohnson** [comment]
@vojtechmzl @TheoChevalier I came across these in the brainstorm doc. They aren't culturally-specific but they are locale-specific and reference our work in the EU this Fall. They might also make good tests: 

In 2016 Mozilla stood with the people of [COUNTRY] to reform outdated copyright laws and protect the Internet. Today we are asking for your help. Please donate to Mozilla so that we can continue to stand for a free and open Internet in [COUNTRY] and around the world. Donate today.

In 2016 Mozilla launched a campaign in [COUNTRY] to reform outdated copyright laws and protect the Internet. To keep this campaign going, we are asking for your help. Please donate to Mozilla so that we can continue to stand for a free and open Internet in [COUNTRY] and around the world. Donate today.

This year more than 100,000 people in the EU signed Mozilla’s petition to reform outdated copyright laws and protect the Internet. Today we are asking for your help to continue standing with people of [COUNTRY] for a free and open Internet. Donate today.

Thoughts about testing these?

**Comment by TheoChevalier** [comment]
@HPaulJohnson  yeah, they are more than locale-specific, they are country-specific. So that means we can reach out less people than with country-agnostic snippets.

In the French community, several people thought it was more impacting to mention Europe as it’s where Mozilla is taking action. So we get inspired by the copy you mentioned to create the snippet I posted in https://github.com/MozillaFoundation/Advocacy/issues/629#issuecomment-263429560
I think it’s great to mention the Copyright campaign, but I’m not convinced about the country part vs. Europe

**Comment by TheoChevalier** [comment]
Just received formal/informal German variants: https://docs.google.com/a/mozilla.com/document/d/10GV0ectp7oegUXP7XsevRdpCIeT5K5ZWz3Ti0ITnzIA/edit?usp=sharing

**Comment by vojtechsedlak** [comment]
Hey @TheoChevalier, could we translate the three variants that @HPaulJohnson outlined above into German, French and maybe Spanish and Polish? I think we could even test referencing a specific country vs referencing Europe. This test would tie in nicely with the icon test that's running this week, possibly equipping us to run highly targeted snippets towards the end of the campaign.

**Comment by vojtechsedlak** [comment]
The test we ended up running did not yield fully conclusive results. In some locales, such as France and Spain we found that mentioning a country name in the snippet copy can improve click-through rates, but that wasn't the case for Germany. In addition to locale-specific copy, we've also tested the following variants of the content theme:

- health of the internet
- statistics
- protect the net 
- fight for the net
- meme culture

Performance varied across locales and no overall winner emerged. Following the test, each locale was served the best performing snippet variant.

Full results of the test can be found [here](https://docs.google.com/spreadsheets/d/158srlDoQGL3AEKCk5ThudVHW3MSxVV_05YdxRFvoIZc/edit#gid=0).
