### ISSUE TITLE
Design: Email callouts for EOY email #3 and #4

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#642]
Create two additional email callouts for:
Email 3 personal impact story and email 4 ...  Listical, fun and eye catching: Top XX things you'd have missed in 2016 on the internet without Mozilla.

Post content here: https://goo.gl/l5bwTR

*Start date: November 28, 2016* 
*Due date: December 12, 2016* 

CC: @HPaulJohnson @stephaniemcv

**Comment by Matt-Holland** [comment]
@lovegushwa : this ticket has a due date of Dec. 2, although that seems pretty early for a "final push" item... When do you think we really need to have this item finished?

**Comment by stephaniemcv** [comment]
We need images a few days before send date for routing through the review group. Here are send dates if that's helpful.

- Email 3 - Personal Story is scheduled to send 12/15. (This send has the most flexibility since it's the week after workweek)
- Email 4 - Listical is scheduled to send 12/27. No flex on this date.

**Comment by lovegushwa** [comment]
@stephaniemcv looks like we are good to go on email 3? ... Let's chat about email 4 tomorrow if possible.

**Comment by stephaniemcv** [comment]
We done did it. Your team does good work @lovegushwa!
