### ISSUE TITLE
Design: Hero image for EOY fundraising email #3

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#666]
Detailed description of work: EOY fundraising email #3, scheduled for Dec. 15, will be a template test ... our standard design with callout box on the right, versus the alternate design with a hero image on top.  Will get more info including dimensions/specs ASAP, but just wanted to get this one up on the board.

*Start date: December 5, 2016* 
*Due date: December 12, 2016* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @lovegushwa @HPaulJohnson @Matt-Holland @stephaniemcv

**Comment by beccaklam** [comment]
Hey @WillatMozFdn here is the link to the hero image for email #3. I worked with action shot #2 since it was the strongest. Let me know if you need anything else! https://drive.google.com/open?id=0BzuBOR2VJQqUd1ZDR2ZSZi1FVUU

**Comment by stephaniemcv** [comment]
We need a line of text @caltrider @WillatMozFdn and a donate "button" on the image. It can't just be an image or at that height we drive the CTA to far down.

**Comment by stephaniemcv** [comment]
@caltrider @WillatMozFdn What about:
"Help support the next generation of makers and builders."

**Comment by beccaklam** [comment]
Hey @WillatMozFdn so I redesigned the header and put the image choices here: https://drive.google.com/open?id=0BzuBOR2VJQqUQmNrRUc5UC03cUk I wasn't sure how you were working around retina screens so I put some choices in there for you. The 1200x600 ones should work fine for retina but not sure how they look for average screens. Perhaps try both versions out (600x300 and 1200x600) for both regular and retina and see which one's sharper? If you could forward me the emails that would be great since I have both screens and could test both.

**Comment by beccaklam** [comment]
@WillatMozFdn @stephaniemcv @caltrider Just saw @stephaniemcv 's comments now. Let me know what text you decide on and I'll add it in bright and early tomorrow.

**Comment by WillatMozFdn** [comment]
@stephaniemcv  -- "Help support the next generation of makers and builders." -- great by me!!
@caltrider  -- you good w/that?

**Comment by caltrider** [comment]
@stephaniemcv @beccaklam @WillatMozFdn Works for me.

**Comment by beccaklam** [comment]
@WillatMozFdn @stephaniemcv @caltrider @lovegushwa Here is the new hero image for email 3: https://drive.google.com/open?id=0BzuBOR2VJQqUZlM3anRQaWRoLUE Let me know if you need any changes!
