### ISSUE TITLE
Basket integration with stopgap copyright page. Sync app accept client-direct messages or build other server-side app

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#719]
Should we send be sending our calls to basket/SQS from client, or use a server-side app.

cc @cadecairos Is these more to this question?

Should we make a list of pros and cons?

If we have a SQS, is this question still valid?

related? https://github.com/MozillaFoundation/Advocacy/issues/718

**Comment by cadecairos** [comment]
a) Send signups directly to Basket
This is the easiest (for us), but I highly doubt the team running basket would be excited to add another custom endpoint, and we also might end up DDOSing them if we get lots of traffic :)

b) Send signups to the [mozilla_webhook_sync](https://github.com/mozilla/mozilla_webhook_sync) app
This is probably the second easiest - since we can piggy back on the existing integration. We'd need to add a custom endpoint for the client app to post form submissions to, and we'd need to ensure the payload we get from the interim app is similar enough to just be a drop in replacement for data coming from the NationBuilder webhook. There is a potential for spam here, but we can mitigate it somewhat with CORS rules.

c) The interim app gets a lightweight server with a post endpoint for form submissions. This endpoint would dump the data into either a new SQS queue for Basket or the existing one (latter is preferred)

**Comment by ScottDowne** [comment]
For signups, we're just going with basket + the server's node back end + hatchet. Right?

@cadecairos Can we close this?

**Comment by ScottDowne** [comment]
We're likely doing this how we did the open data day signups.
