### ISSUE TITLE
Design "Resources" page

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#722]
As per conversations today, the design will be kept simple, with no implied user functionality.

Meta data will be provided by @Melechuga:

- Title
- Author/Org {+ link?}
- Blurb
- Format (e.g. pdf, video, website)
- [Image ?]
- Links
- Languages available

All metadata should be displayed on the page, but without any user interactions other than linking (e.g. no sorting/filtering)

**Comment by hannahkane** [comment]
Aiming to have this by Friday, to maintain overarching timeline. @beccaklam - feel free to separate this into a wireframe ticket and a UI ticket if you'd like.

**Comment by beccaklam** [comment]
@Melechuga Is there where I can find the meta data? https://docs.google.com/document/d/1oH0AHjP_SpCtatrmPxkOEJDzz8sUWQ_P5PGBdqCjNgU/edit

**Comment by beccaklam** [comment]
@Melechuga @lovegushwa @hannahkane Here is the rough wireframe of the Resources page. @Melechuga I'm assuming I'm waiting on the copy to be finalized (re: copy and paste-able?) It would be great if the copy could be as succinct as possible! Here is a link to a redpen for comments: https://redpen.io/rc76666a6333e8a644
![resources desktop wireframe](https://cloud.githubusercontent.com/assets/20977376/23265575/0eea28d0-f9b3-11e6-8dff-aea96070c192.png)

**Comment by hannahkane** [comment]
Nice, speedy work, @beccaklam! I left a few comments on the redpen.

**Comment by Melechuga** [comment]
Thanks @beccaklam! I also added some comments on the redpen.
I've updated the resources meta page here: https://docs.google.com/document/d/1oH0AHjP_SpCtatrmPxkOEJDzz8sUWQ_P5PGBdqCjNgU/edit#bookmark=id.x8ob7xleazg6

Almost all of the resources are in English, as that's the main language being used in Brussels at the moment. I think it's fine for the title "resources" to be localized, and for the page to appear the same in all localized versions -- i.e. I think it's better to have at least English resources instead of nothing in other languages; maybe a discussion with @TheoChevalier would be useful?

It is in Raegan's hands to sign off by Monday. Thanks!

**Comment by beccaklam** [comment]
@hannahkane @Melechuga @lovegushwa @TheoChevalier @ScottDowne Updated wireframe based on Melissa's resource meta page and redpen feedback: https://redpen.io/waf214479b2004f6d1
![resources desktop wireframe](https://cloud.githubusercontent.com/assets/20977376/23308169/38b468cc-fa78-11e6-8644-d09a7a1ac3ba.png)

**Comment by hannahkane** [comment]
Nice, @beccaklam! Comments in the redpen.

**Comment by Melechuga** [comment]
Sign off complete! Resources meta page here: https://docs.google.com/document/d/1oH0AHjP_SpCtatrmPxkOEJDzz8sUWQ_P5PGBdqCjNgU/edit#bookmark=id.x8ob7xleazg6

Per comments, only documents that are PDFs should have their "format" listed. Only one resource is multilingual (English + German).  All links to organizations should be there; let me know if anything is missing. Not sure what you want to do for images; happy to discuss that next. Thanks @beccaklam!

**Comment by ScottDowne** [comment]
@TheoChevalier is there anything I should know about this page and l10n? Has the process for translating this begun?

**Comment by hannahkane** [comment]
Hey @ScottDowne - I emailed on Feb 22 with some notes about this.

Since we don't have a lot of content in non-English languages, and because we identified that we're really targeting our partner orgs with this page, we could choose to make the Resources page available only to users in EN locales. We could still indicate visually the non-EN resources, but we wouldn't localize the page and we would hide the nav link for non-EN locales.

What's the feasibility of hiding a nav link based on locale?

**Comment by ScottDowne** [comment]
@hannahkane I think I remember talking about this now.

Yeah, hiding a nav link is no biggie. I'll do that now.

**Comment by Melechuga** [comment]
@hannahkane Does this mean that anybody who signs in from a non-en ISP (france, germany, etc) wouldn't see the resources? Or would they have to choose "English" as their language in order to see them?

**Comment by ScottDowne** [comment]
Yeah. It would mean they have to choose English to see them.

**Comment by Melechuga** [comment]
Would it be possible to add a line that says "See more resources in English" that is both localized and links to the /en version of the resources page? That way people who are accessing the localized site know that there are more resources available in English. 

cc @beccaklam @hannahkane

**Comment by ScottDowne** [comment]
@Melechuga I would also add @TheoChevalier to the above discussion.

**Comment by TheoChevalier** [comment]
I’m a bit concerned by the length and the expansion rate in the header for the locales, but we could do that if we want them to check the resources, yes. It’s better if we can make a decision soon, though, since it requires a new string and we have pending changes.
@Melechuga What about “More Resources (in English)”? Does that look good to you as well @beccaklam from a design standpoint?

**Comment by Melechuga** [comment]
@TheoChevalier That looks good! Thanks.

**Comment by beccaklam** [comment]
Hey @Melechuga I'm just wondering what's the goal of having the 'More resources (in English)' on the non-EN locales? The reason we decided to hide the resources on non-EN locales is because we thought it would be disrespectful to offer resources not in that person's language. I think sometimes it's better not to do something at all if you can't do it well. Also, this is only a stop gap solution so when we have more non-EN resources we can add them in then.
CC:@TheoChevalier @ScottDowne @hannahkane

**Comment by beccaklam** [comment]
@Melechuga @hannahkane @ScottDowne @lovegushwa Resources Page UI:
All highlighted texts are links. If we could style the hover interaction like the internet health report that would be great @ScottDowne https://internethealthreport.org/v01/
https://redpen.io/pw36aad51a77ac7360 <-- redpen for comments
Still working on tablet and mobile, will get those done by EOD.
![resources desktop ui](https://cloud.githubusercontent.com/assets/20977376/23414271/56a04638-fda9-11e6-967e-70dcb2108705.png)

**Comment by hannahkane** [comment]
Thanks, @beccaklam. I think the page looks great. I just left one question on the redpen.

**Comment by beccaklam** [comment]
Re:@hannahkane your question in the redpen: do you think it would be a good idea to take away the language drop down menu on the resources page? CC: @TheoChevalier @ScottDowne @Melechuga

**Comment by hannahkane** [comment]
Per discussion we're having right this minute in stand, we're going to hold off on any messaging to non-EN users for now. Can reconsider post-MVP.

**Comment by hannahkane** [comment]
Decision re: language selector—we'll hide it on the Resources page. cc @ScottDowne 

Design = final.
