### ISSUE TITLE
DUE FEB 27: Create comp

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#728]
Dependent on final copy: #727 

Comp should be based on copyright page design, but requires replacing copy, removing language selector, removing "Resources" page in nav, different header image

**Comment by hannahkane** [comment]
@beccaklam - do you have everything you need for this now?

**Comment by beccaklam** [comment]
@hannahkane Yes, I'm aiming to have this done by EOD!

**Comment by hannahkane** [comment]
rad. Thanks!!! 👍

**Comment by beccaklam** [comment]
Hi @hannahkane here is the desktop comp for the Open Data Page. It looks a bit different because we need to use Arvo (typeface) instead of Tesla. It's not as great but it will have to do. This is the redpen for comments: https://redpen.io/p/ma1f0579fd364383ec Also, @ScottDowne you can reference this comp to fix the font/spacing issues for ticket #738. Working on getting tablet and mobile out for this comp by EOD.
![open-data-desktop](https://cloud.githubusercontent.com/assets/20977376/23381885/28925fce-fd0e-11e6-92d9-011c702d1e3d.png)

**Comment by beccaklam** [comment]
@hannahkane @ScottDowne Tablet and Mobile:
https://redpen.io/p/ma1f0579fd364383ec <-- redpen for comments

Also, @hannahkane I'm flagging the fact that the copy is a bit wierd near the bottom where the last paragraph has the title 'Agree' followed by 'Then add your name' and then the form 'Do you agree' followed by 'If so, add your name'. The language is very similiar and because in the tablet portrait and mobile layouts these sections are side by side it's a bit weird. Ashley flagged the same thing in the copy https://docs.google.com/document/d/1juXdq413TCG-M2WV7qZvJe9IOxO-jsFVCexgSV40c8k/edit?ts=58addd12 but because it was thought the sections would be laid out on separate parts of the page (which they are on desktop) it was thought to be a non-issue. However, now that it's laid out on tablet and mobile I think it may be a problem. Let me know if you understand what I'm saying.

![open-data-tablet-portrait](https://cloud.githubusercontent.com/assets/20977376/23381128/545dbc8c-fd0b-11e6-986e-bc518303cadb.png)
![open-data-mobile](https://cloud.githubusercontent.com/assets/20977376/23381129/5612ad6c-fd0b-11e6-886a-489f40784611.png)

**Comment by hannahkane** [comment]
@beccaklam - comps look great. I do see what you're saying about the repetition in the language. I'd suggest we cut the "Agree?" paragraph entirely. I don't think it's adding anything that isn't also covered in the "Do you agree?" paragraph. (Well, it has the "Share with your friends and family" line, but I honestly think that's going to get lost here anyway.)

What do you think of that idea?

**Comment by beccaklam** [comment]
@hannahkane That sounds good to me. We'd have to check with @shaghdoosti  first though

**Comment by shaghdoosti** [comment]
Hey - yes, let's cut the agree paragraph.

**Comment by hannahkane** [comment]
@ScottDowne will cut the para in the implementation ticket. Closing design.
