### ISSUE TITLE
DUE MARCH 2: QA

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#730]
Staging is here: https://iheartopendata.mofostaging.net/en-US/#about

## Devices
 - [x] Desktop
 - [x] Tablet
 - [x] Mobile

## Browsers (latest version of each)
 - [x] FF
 - [x] Chrome
 - [x] IE (@hannahkane to QA this)
 - [x] Safari

## Front end functionality to test
 - [x] All links work as expected (including Privacy and Terms in form, all footer links)
 - [x] Navigation works as expected (including "Sign Me Up" button in hero)
 - [x] Sign-up form works as expected 
   - [x] field highlights work
   - [x] tabbing through fields works correctly (desktop)
   - [x] user receives error message if they don't provide an email
   - [x] user can submit form with only email field completed
   - [x] Users coming via email will not see email sign up language on form ( @WillatMozFdn and @stephaniemcv to QA)
  -  [x]  user receives success feedback upon submission (including email receipt?)

## Backend functionality to test
  - [x] Users info is added to google sheet
  - [x] -> Salesforce ( @stephaniemcv and @WillatMozFdn to QA this)

## Design QA
  - [x] Production matches comps ( @beccaklam to QA this )

## Content to check
   - [x] Spelling errors or typos
   - [x] No awkward line breaks / spacing / layout issues

**Comment by hannahkane** [comment]
@beccaklam - I'm tempted to check the box for "Production matches comps" in the list above (except I do think the stuff in #738 needs to be resolved), but I feel like you're the right person to be checking that box. 

Can you be the person to officially OK the design of the site before we push to production?

**Comment by beccaklam** [comment]
@hannahkane Sounds good!

**Comment by beccaklam** [comment]
Some design QA: 

- [ ]

**Comment by WillatMozFdn** [comment]
@ScottDowne -- can you let me and @stephaniemcv know the two versions of the URL (one for people we're driving there via email, vs. one for everyone else) as soon as they're ready?  We'll need the former tomorrow, of course, to build the email itself...)

**Comment by beccaklam** [comment]
@hannahkane @ScottDowne @lovegushwa 
Some design QA post-launch:

**Priority 1**

- [x] view port content overflows, needs to max out opposed to overflow
<img width="1280" alt="screen shot 2017-03-02 at 2 52 05 pm" src="https://cloud.githubusercontent.com/assets/20977376/23525840/d9539da4-ff5d-11e6-8cf1-40f5ff5074ec.png">


- [x] Widen the container for the sign up form, it's getting a bit too narrow for the copy in screen sizes at widths 1280px to ~1800px
<img width="1277" alt="screen shot 2017-03-02 at 3 29 16 pm" src="https://cloud.githubusercontent.com/assets/20977376/23525837/d5d63b46-ff5d-11e6-9ad2-70e8325485c7.png">


- [ ] Mobile needs a sticky button that sits at the bottom of the page like copyright v2. Button will direct user to form at the bottom of the page

**Priority 2**
- [ ] Change footer links to Fira to be consistent with mozilla.org

- [ ] Add in functionality (media query for view port?) so that tablet also has a fixed 'cover-page' where the 'get involved button' is always above the fold

- [ ] On desktop/tablet the form should become sticky once it gets into view on a user's screen. We need to work on cutting down the amount of copy so this can accommodate for a variety of screens.

**Comment by beccaklam** [comment]
@hannahkane @ScottDowne  I'm checking off my Design QA check box. The ONLY thing that I feel is important to get done before launch or soon after is fixing the view port content overflow issue (the first item outlined above). Otherwise, I feel like how the site looks right now is good enough to ship to production. There's still work to do as I've outlined above, but these things can be tackled after launch. Though if the items under Priority 1 could get done before launch that would be amazing, but I don't think it's a top priority (except item 1). CC: @lovegushwa

**Comment by ScottDowne** [comment]
Here is the link to test turning off signup https://iheartopendata.org/en-US/?subscribed=1#get-involved

**Comment by TheoChevalier** [comment]
Shouldn’t we rewrite the URL once it’s loaded? People could share this one on social media, right?

**Comment by WillatMozFdn** [comment]
In theory, someone *could* manually copy the URL from their address bar
before they actually sign on the right hand side ... but I think that will
be pretty rare/edge case behavior.  The share link down at the bottom, and
the post-signing share functions (both of which are ShareProgress) do not
include that querystring ... so I'm not very worried about it.

That being said, if it's an easy thing to re-write the URL after the page
has loaded (without the un-needed checkbox for those already-subscribed)
... there's no compelling reason NOT to do that AFAIK?

 - W

**Comment by hannahkane** [comment]
Ok, I've tested the following:
 - [x] if you check the email updates checkbox, you get the double opt-in email
 - [x] if you don't check the email updates checkbox, you don't get the double opt-in email (at least not within 10 minutes)
 - [x] if you use the qs version, you *don't* get the email updates checkbox

I can't check what's happening in SF, but I'm going to call this ticket good. Will move @beccaklam's non-blocking design QA to a separate ticket.

If someone wants to open a new ticket for the edge case described above, please do!

**Comment by ScottDowne** [comment]
I'm hesitant to change the url once it's loaded, because what if someone who opened it from an email hits refresh after page load, for whatever reason? I think the question is which is less of a fringe case, and consider one of these options requires no action ;)

**Comment by ScottDowne** [comment]
For future campaigns, and with how urls work, I think we should consider another strategy for targeting certain audiences.

Some long-winded, half-baked, brain-stormy ideas:

One idea I had was we don't hide or remove certain CTAs on certain versions, but just change how prominent they are in the UI. Let's use this campaign as the example. If instead of turning off the sign up checkbox, we add another button somewhere else in the form that's less prominent than the signup petition that like "Not a member, consider signing up". On the flip side, or main snippet traffic could see something like "Already a member, go here to just sign the petition."

We could also revisit the copy on this bit, if there are issues and fringe cases in the channels. Something like `[ ] Not a member? Consider receiving news from us.` Which we might be able to display as is, in all channels.
