### ISSUE TITLE
Infrastructure check: EU snippet donations July 21 - 26

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#74]
@ScottDowne and @cadecairos just want to make sure that our back-end (Stripe; etc) is good to go for this campaign: https://docs.google.com/document/d/1sVtIcqsvb713KhdRUMYVGdFzUoUNLWQDNi9Y7Cr8F08/edit

We'll need to give URLs to the snippet team for these as well.

**Comment by cadecairos** [comment]
From a monitoring standpoint, we're better off than last year, since I've put a bunch of effort into that since March. From a scaling perspective, we're still set up to autoscale should load cause service times to increase. 

There's also more monitoring on dependent services we didn't monitor last year, like sawmill, which sends our donation receipts.

**Comment by valianttry** [comment]
I just looked at Google Analytics and can confirm there are successful donations through the forms for these locales.

**Comment by cadecairos** [comment]
how much traffic should we anticipate?

I'm going to triple check that donate is A-OK to handle an increased load, and that Auto scaling is enabled.

**Comment by valianttry** [comment]
30,000 - 50,000 page views a day (roughly)

**Comment by cadecairos** [comment]
Glad I looked, because auto scaling was disabled! Must've been from when I reset my 2FA device - it regenerated the secret key I set up with the auto scaling provider!

It's now re-enabled.

**Comment by cadecairos** [comment]
I'd say we succeeded in not falling over 👍
