### ISSUE TITLE
Hide disclosure for people coming to the Open Data Day form direct from email

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#757]
EDIT: 

Per stand-up discussion: we're going with [option two](https://github.com/MozillaFoundation/Advocacy/issues/757#issuecomment-283716562) from the comment below, since all of our petitions should be treated as email collections.

Scott's TODO:
 - [x] add query string to url that will go out in the email; give users a view of the site that doesn't have the email sign-up language
 - [x] add checkbox

-----

Perhaps I'm missing it but I don't see anything on the Open Data Day "add your name" form at the right that will prevent someone coming to this petition from an email source from getting the ...

"By signing, you accept Mozilla’s Terms of Service and Privacy Policy, and agree to receive occasional emails about campaigns from Mozilla. You can unsubscribe at any time."

...disclosure.  It's unnecessary (we **already have** permission to email them) and will definitely depress responses and induce confusion. (We're using email to send them to a form that asks them to opt in to email -- ??)

Can we turn off or hide that disclosure via a querystring added to the URL that goes out only over email, that is, the link in the email (only) includes a variable like "?subscribed=1" and this hides the disclosure block?

*Start date: March 2, 2017* 
*Due date: March 3, 2017* 

CC: +

**Comment by shaghdoosti** [comment]
This is a really good point. @ScottDowne is this possible?

**Comment by ScottDowne** [comment]
There is no technical reason why we couldn't do this.

**Comment by hannahkane** [comment]
Thanks for raising this. It's related to another issue that came up today about how to handle forms where we're doing two distinct actions (petition + email collection).

It sounds like we need to do one of two things:

1) Treat this as purely a petition site—that is, not use it to collect new emails. In this case, I believe we'd remove the language related to email signups, and wouldn't add any new users to our emailable list.

2) Treat this as both a petition and a signup—in this case, we'd do the conditional described in this ticket (email sign-up language for those who *aren't* coming from the email we sent), AND we'd have to add a checkbox, since this form is doing double-duty.

Can we discuss at stand at 9:40am PT in the Advocacy vidyo room?

**Comment by shaghdoosti** [comment]
Hey -

Let's discuss at the stand. But the first option isn't tenable - there are very few campaign moments when a petition isn't also a sign-on. We should figure out how to avoid taking people already on our list through signing up again - but generally with a petition we want anyone who isn't on the list to be able to join the movement.

**Comment by hannahkane** [comment]
Updated original comment to reflect discussion at stand.

**Comment by ScottDowne** [comment]
removing the checkbox should be on staging very soon: https://iheartopendata.mofostaging.net/en-US/?subscribed=1#get-involved

I'll close this once I confirm it's working on staging.

**Comment by ScottDowne** [comment]
Done and done.
