### ISSUE TITLE
Replace font on the EU Copyright Campaign site

### ISSUE THREAD

**Issue by mathjazz** [MozillaFoundation/Advocacy#775]
The [Arvo font](https://www.fontsquirrel.com/fonts/arvo) used on the EU Copyright Campaign site does not support many (most?) of the European languages.

The following 5 localizations appear broken:
https://changecopyright-org-staging.herokuapp.com/sl/
https://changecopyright-org-staging.herokuapp.com/sk/
https://changecopyright-org-staging.herokuapp.com/lt/
https://changecopyright-org-staging.herokuapp.com/hr/
https://changecopyright-org-staging.herokuapp.com/cs/

And there could be more.

**Comment by TheoChevalier** [comment]
Thanks again for filing that, @mathjazz, definitely something to fix.

https://changecopyright-org-staging.herokuapp.com/bg
https://changecopyright-org-staging.herokuapp.com/ro
Have issues, too.

Both Fira Sans Condensed and Arvo are broken, and it seems the fix we have for Fira Sans Condensed for `cs` locale does not even work? https://github.com/mozilla/copyright/blob/master/src/pages/index.js#L17-L19 

@beccaklam @natalieworth @lovegushwa do we have any alternative font we could use for those locales? At least Open Sans should work. In the case of Fira Sans, I wonder if it’s an issue with the Condensed version only or an issue with the version hosted on Google Font, because we’re using several versions of Fira Sans on https://transvision.mozfr.org and it works for those locales.
CCing @ScottDowne too

**Comment by ScottDowne** [comment]
Should be fixed now (or in a moment once staging finishes its build)

Thanks for finding this.

**Comment by ScottDowne** [comment]
Should be good. Feel free to reopen if it doesn't work, or if you see something slightly different feel free to open a new issue! Thanks again for finding this.

**Comment by mathjazz** [comment]
I'm looking at https://changecopyright-org-staging.herokuapp.com/sl/ and I see a different font, but with the same problem.

https://cl.ly/1l0K3f0v453b

**Comment by ScottDowne** [comment]
Hm, this is what I see: 
![what-see](https://cloud.githubusercontent.com/assets/197334/23803818/bcc101a8-0585-11e7-8a4a-ba38f4e2fc4f.png)

Is that what you see, and is there still something weird about this?

I know fira sans + linux can have issues. Might be that. I should probably fix that anyway.

**Comment by mathjazz** [comment]
Yup, it looks different on my screen (OS X 10.11), Aurora. Check s and š for example.

![my screen](https://cloud.githubusercontent.com/assets/626716/23803945/867bab60-05b8-11e7-8f62-6b18ca62ef1b.png)

**Comment by ScottDowne** [comment]
Ah, yeah, I see it. Trying a fix. Shouldn't be long.

**Comment by ScottDowne** [comment]
The fira font on google fonts for whatever reason is pretty weird. I'm moving to "https://code.cdn.mozilla.net/fonts/fira.css" and seeing if that fixes it.

**Comment by ScottDowne** [comment]
OK, try now. https://changecopyright-org-staging.herokuapp.com/sl/

**Comment by mathjazz** [comment]
Helvetica FTW! Love it! Thanks!

**Comment by ScottDowne** [comment]
blah, ok, backing out.

**Comment by ScottDowne** [comment]
Must be reverting to a system font?

**Comment by mathjazz** [comment]
Oh I thought you intentionally went for Helvetica! :D

**Comment by ScottDowne** [comment]
I wish life was that simple :P

**Comment by ScottDowne** [comment]
OK, building another solution.

1. Loading it off the mozilla cdn failed because I failed to add rules to the csp.
2. Fira Sans Condensed didn't have a cdn that I can find (yet) which we use for inputs, buttons, labels, and errors. So we're still loading that from google fonts. Hopefully it doesn't have the same issues for you as regular fira sans from google fonts. Hopefully the mozilla cdn als doesn't have these issues for regular fira sans.

**Comment by ScottDowne** [comment]
OK, built and on staging. Hopefully we got this now: https://changecopyright-org-staging.herokuapp.com/sl/

**Comment by mathjazz** [comment]
Well done! Checked sl and other locales and they all LGTM. Thanks!

**Comment by ScottDowne** [comment]
Thanks for finding and for your patience helping us debug.

🚀
