### ISSUE TITLE
Content and engagement: draft plan for News Matrix and SafetyFirst tips

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#787]
These questions came up in conversation with @HPaulJohnson:
 * Should users be able to choose to get Safety Tips OR News Matrices OR [future content vehicles]? Or should it just be a single opt-in to get everything?
 * If the latter, what's the best way to present this on the landing page, since they're pretty different content types, and users' motivations for wanting to receive them might be different? Should we have a page for each one, but the ongoing engagement is the same regardless of where the user signs up?
 * What's the frequency with which people will receive this content? Should they expect to receive it on a given day of the week? 
 * Do we want to suggest that the content is a finite series? e.g. something like "Sign up to receive the 10 tips you need to be a Safety Pro"? Or is it best to leave it open ended?

cc @caltrider @lovegushwa @beccaklam @natalieworth @ScottDowne @WillatMozFdn @stephaniemcv

**Comment by stephaniemcv** [comment]
- My vote is single opt-in as that is what our current infrastructure can support. What is the timeline for launch of this landing page?

- It would be an intriguing test to see what content type encourages more email signups. Ongoing engagement would depend on the desired frequency of content published, that would determine if we could reasonably support a unique engagement plan for each content type. 10 different content types delivered weekly is probably not realistic. How many content types are being considered? 

- Frequency depends on content creation and support capacity. It's not unheard of to set the expectation for delivery on a specific day of the week. But it will erode subscriber trust if we over promise and then under deliver.

- If we choose a finite series, I would love for us to build an automated Journey in SFMC. However, this would require that all content for the series is created ahead of time. I think if we can't commit to that then it's best to leave it open ended.

**Comment by caltrider** [comment]
My thoughts:

_What's the frequency with which people will receive this content? Should they expect to receive it on a given day of the week?_

The plan for the News Matrix is to have it come out every Friday once we get it up and running.
The plans for the Tips are still being worked out.  I would like it to be a tip of the day where we can get a bulk bunch of tips (say a month or two worth at a time) approved and then have them queued up and ready to go. And then if there is some breaking news or something that requires rapid response, we can turn a timely tip around then and get it out instead of one in the queue.

_Do we want to suggest that the content is a finite series? e.g. something like "Sign up to receive the 10 tips you need to be a Safety Pro"? Or is it best to leave it open ended?_

Right now, in my mind, both the news matrix and the tips are open ended. 

_If the latter, what's the best way to present this on the landing page, since they're pretty different content types, and users' motivations for wanting to receive them might be different? Should we have a page for each one, but the ongoing engagement is the same regardless of where the user signs up?_

As I envision this, it seems like both the tips and the matrix would work best by having their own pages we can customize to their style of content. And then we can test on each page which opt-ins and sign-ups work best.

**Comment by lovegushwa** [comment]
Questions for tomorrows privacy tips/news matrix content meeting:
- how much archive do we show / what's our carrot / incentive ?
- can users subscribe to one list (privacy) and not the other (news matrix)?
- how does the subscription work, is content delivered through email OR email and social?
- how is our email audience different than social? Age, demographics etc?
- what's our per- channel strategy? ie. do we ask our twitter followers to give a email address to get special content not posted to twitter.
- how are we advertising / promoting these landing pages?

**Comment by stephaniemcv** [comment]
More info based off of @lovegushwa's questions:
- **can users subscribe to one list (privacy) and not the other (news matrix)?** In our current architecture, no. To support this we would need to schedule new work on Basket and Salesforce with MoCo to build out. This does not look viable for the upcoming sprint (04 Apr 2017-20 Apr 2017) Then there's the issue of list vs interest; if we create new list, we risking silo-ing these subscribers. An interest would allow more flexibility in that they would get all our Mozilla emails and then their selection (privacy vs news matrix). Another question on my mind, is what to do about current subscribers? How are they invited into this new content? We can't send them to a signup landing page, because they already are signed up. So what's the messaging for that audience?
- **how is our email audience different than social? Age, demographics etc?** We don't know. Really the most demographic data we collect is language and country and even then, it is a small portion of our list that has that.

**Comment by hannahkane** [comment]
Taking this conversation to [the doc](https://docs.google.com/document/d/1-s7aNACXlOv8GpHk5zLSfxLolFwLSGy9P_t-wJT6uUM/edit?ts=58daac59), which is probably a better place for it.

**Comment by hannahkane** [comment]
This ticket is crazy. Closing and opening a newer one reflecting the current state of things.
