### ISSUE TITLE
Content and Email: Finalize content and engagement strategy for News Matrix

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#793]
- [x] @WillatMozFdn to document process for creating/sending emails, including workflows for appointment content such as the weekly News Matrix email. 
 - [x] Confirm locales for email: US, CA, UK, AU (I'm assuming we won't support these locale distinctions for the promo/archive page)

Decisions to be made:
 - [x] Will we send the News Matrix email weekly OR bi-weekly / alternating with SafetyTips email?
 - [x] How will we resolve the formatting constraints for the email?

**Comment by hannahkane** [comment]
@caltrider and @WillatMozFdn - we're getting close to done on the News Matrix design, and will start the build for the landing page very soon. I want to make sure we're also 💯  on our content strategy and email engagement plan. I believe the items above are the only things outstanding.

**Comment by hannahkane** [comment]
@caltrider and @WillatMozFdn - just pinging on this. Do we have final decisions on the items in this ticket?

**Comment by caltrider** [comment]
@WillatMozFdn @hannahkane 
@lovegushwa is working on a design template for the news matrix that will hopefully make it a rocking email send.  That being said, I'm good to send either weekly or bi-weekly.  The content will be done weekly regardless, so which ever works best.  And hopefully, down the road, we'll have a system set-up where people can opt-into getting this sort of content as they choose.

**Comment by hannahkane** [comment]
Decisions made at stand, with @WillatMozFdn, and based on @caltrider's comment above:
 * We'll start with emails to en-US, en-CA, en-UK, and en-AU audiences. This decision is based on the perception that content will be most relevant to these audiences.
 * We'll start with an every-other-week cadence for sending out the news matrix emails. This decision was based partly on workload concerns, and partly on an awareness of other regularly-scheduled emails.
 * @lovegushwa's email template will address formatting issues 

Additional questions raised:
 - [x] Email template likely requires add'l coding time for @WillatMozFdn. Will and Jen to clarify the timeline for the first send.
 - [x] What will be our measure of success for the News Matrix emails? In other words, how will we know whether the emails are accomplishing our goals and whether to keep sending them? cc @vojtechmzl @caltrider

**Comment by caltrider** [comment]
@hannahkane @vojtechmzl @lovegushwa 
I'd really like to track email sign-ups driven from this as well as social shares.  
@vojtechmzl any other ideas for things we can/should track?  Blog views?  Reddit views/comments?
Social engagement?

**Comment by vojtechsedlak** [comment]
Based on the project brief, the key objectives of the News Matrix are to grow our following on one hand, and engaging our existing community on the other. As such there are two sets of metrics that we can keep an eye on.

Overall, it seems like the underlying questions are:
-  How will existing community members respond to the matrix?
    - What is an acceptable churn? What is an expected OR/CTR & Unsubscribe Rate?
- How will the news matrix stand out on social and in paid channels? 
    - How successful will it be in capturing attention? What is an expected Click-through-Rate
- How will the news matrix help us develop relationship with our audience over time?
    - How do we know if people return to the news matrix regularly?

The assumptions underpinning this project are as follows:
- The news matrix can help drive new signups to Mozilla's list
- People within our community are interested in receiving this content
- The news matrix can attract attention on a regular basis and drive engagement with content it highlights.

### Given the above, the metrics that I think we should track are divided into the two categories:

- Community Growth
  - Total # of impressions across channels
  - Click-through rate to landing page
  - Landing page email signup conversion rate
  - Total # of new signups

- Community Engagement
  - Engagement conversion rate (people clicking on the matrix links / people landing on the website)
  - Social resonance rate (people liking + sharing + commenting / people seeing the matrix) 
  - Engagement over time (comparison of engagement metrics over time)
  - Click-to-Open Rate and Unsubscribe Rate for existing email community  

Since none of these metrics currently have a comparable baseline, we will need to establish those after a few iterations of the news matrix. Let me know if this makes sense, or if there is anything else that needs to be articulated.

cc @caltrider @hannahkane @lovegushwa

**Comment by hannahkane** [comment]
@vojtechmzl - thanks for this; this is great.

One clarifying question - Does "click-through rate to landing page" refer to clicks from non-email sources? Or would it also include people who click through from the email? I wonder if there's a reason to distinguish between those two, since people clicking through from the email are *already* subscribers, so our ask of them is different.

**Comment by vojtechsedlak** [comment]
great question @hannahkane. The idea here is indeed to focus on non-email sources, which would be contributing to the first objective of community growth. We will definitely be looking at email performance, but as part of the second, engagement-focused bucket of metrics.

**Comment by hannahkane** [comment]
Thanks, @vojtechmzl.

OK, I think we've checked off all the boxes for this ticket and have a solid strategy and plan for the news matrix. Hooray!

Closing this ticket, though if anyone still has outstanding questions or concerns, please feel free to re-open it.
