### ISSUE TITLE
Design: email template for news matrix email

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#794]
@lovegushwa - can you add details?

**Comment by hannahkane** [comment]
@lovegushwa - and can you assign it to someone?

**Comment by lovegushwa** [comment]
Ok folks, here is a draft of the template. We might want a little more context in our first send but for now I have added the word "introducing" before "this week in the web."  ... It can be removed after we introduce this to our list. 

@WillatMozFdn @stephaniemcv @hannahkane @caltrider @beccaklam let me know your thoughts before I knock out a final version. 

![matrix-email-v1- 2x](https://cloud.githubusercontent.com/assets/12228435/24675030/84945918-1932-11e7-8dec-d938577564b9.png)

**Comment by stephaniemcv** [comment]
I feel like the salmon is detracting from the "Tron"-ness of the image. Minus the links in the footer, I'd advocate for a different color. 

I think we should add to the button text. "Interactive Version" is descriptive and doesn't really express the action that we want them to take by clicking the button. Read, investigate, examine, reveal, tour, explore, delve into... as a few suggestions. Check out has been used so often, I'd like to avoid that one.

**Comment by lovegushwa** [comment]
@willeaston i'd rather not use bullets for a list of links. The greater than symbol > is a old-school link convention. We do need something in case the link wraps unless we want to use line spacing to indicate where a link stops and starts. Line spacing could add more hight to the email.

**Comment by lovegushwa** [comment]
@stephaniemcv re "Interactive Version" ... This might not be the best language but we also don't need to drive traffic to the landing page since everything a user needs is already in the email ... ie. "interactive version" is not a hard CTA. Users do need to know the landing page version includes more features if they are interested. @caltrider @hannahkane any suggestions?

**Comment by hannahkane** [comment]
What's the reason for someone to go to the landing page? Is it to view the archives? If so, maybe leave the button off entirely for this first email, and then add it back with "View Past Matrices" as the CTA in the  future.

**Comment by caltrider** [comment]
I agree the salmon color is kinda salmon-y. I'll let @lovegushwa decide what looks best.

Here's an idea for the button text.  Could we test "Interactive Version" versus "Share This". 
The idea being that the people who land on that page from the email will see the share function.

Given that people can get all they need on this from the email (even though the Thinglink version on the website will be cooler), it might be interesting to test and see which button works best.

cc: @hannahkane @stephaniemcv @WillatMozFdn

**Comment by lovegushwa** [comment]
@hannahkane the landing page version will work something http://nymag.com/arts/all/approvalmatrix/approval-matrix-2016-09-05/

So the landing page has some additional interaction when a user mouses over links which is a better experience hence the interactive "interactive version" button.

**Comment by hannahkane** [comment]
Thanks, @lovegushwa. I don't have a strong opinion on the button text. Will defer to others.

**Comment by lovegushwa** [comment]
@caltrider I think thats an interesting test. We might need to tweak the landing page to emphasize share. Perhaps they are directed to the landing page with a some kind of share modal fired.

**Comment by lovegushwa** [comment]
@WillatMozFdn the test email looks great! Two small tweaks: 
(these issues may need to be fixed across all our templates)

Current brand style from MoCo is square buttons can you remove the round corners?
<img width="406" alt="screen shot 2017-04-05 at 10 53 37 am" src="https://cloud.githubusercontent.com/assets/12228435/24719367/54f97a6e-19ee-11e7-9c6b-f02e339f05a0.png">

The text in the Mozilla address should be the light blue color rather than gray.
Also can we replace the "Mozilla" word with the new mozilla logo to match the MIH Newsletter style?

- You can download the logo file here: https://mozilla.ninja/s/Mozilla_Large-Logo_Black-and-white.zip
- Or possibly pull it from the MIH template if you have access. 

<img width="683" alt="screen shot 2017-04-05 at 10 34 52 am" src="https://cloud.githubusercontent.com/assets/12228435/24719415/83829276-19ee-11e7-958c-6f4f39f4f650.png">

**Comment by stephaniemcv** [comment]
@lovegushwa when you say light blue, do you mean the cyan (Hex# 82D1F5) from here: 
https://mozilla.ninja/color-palette/?

My opinion, I think the logo looks weird in the footer, especially since the other two Mozilla's are in text. 

We're working on standardizing all email templates and footers across the org to be brand compliant. Not sure when that rolls out.

**Comment by lovegushwa** [comment]
@WillatMozFdn two small type tweaks i'd like to make. 

Make the header type a little smaller, something like 20px - 24px and that pink box height ~80px. The header text is really large and the text in the image very small and making the contrast between the two a little less should make the difference less jarring.
![screen shot 2017-04-05 at 4 14 54 pm](https://cloud.githubusercontent.com/assets/12228435/24730875/31f92b9a-1a1b-11e7-86b7-b24765d367de.png)

Make the body copy 13px or 14px (currently 14.67px) ... this should help keep most lines from wrapping.
![screen shot 2017-04-05 at 4 15 12 pm](https://cloud.githubusercontent.com/assets/12228435/24730960/b9a60824-1a1b-11e7-8f72-133ed7c85707.png)

**Comment by lovegushwa** [comment]
@WillatMozFdn lets keep the salmon color and keep the button text "interactive version" 
I think the only missing bit is a link to the landing page. @beccaklam also approves of this color ;)

**Comment by lovegushwa** [comment]
@stephaniemcv re the footer logo, I'm asking if we can implement the logo just like the MIH news letter. 
![screen shot 2017-04-05 at 4 31 37 pm](https://cloud.githubusercontent.com/assets/12228435/24731278/cd2ce1a4-1a1d-11e7-87a0-e3475fac7777.png)

**Comment by lovegushwa** [comment]
@stephaniemcv @WillatMozFdn if you want to run a test around color Salmon vs (something else) I would be into it.

**Comment by hannahkane** [comment]
@WillatMozFdn - Has this landed? Assuming the matrix itself is ready to go, will we be able to send the first email this week?

**Comment by hannahkane** [comment]
Reassigning to @WillatMozFdn to finish final tweaks and then close this ticket.

**Comment by hannahkane** [comment]
@WillatMozFdn - can we close this ticket? Is the news matrix email template finalized?

**Comment by WillatMozFdn** [comment]
Yes, close 'er up!  We have a working template ... just need the fresh
content to put in there.
