### ISSUE TITLE
Resolve mobile usability issues on News Matrix landing page

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#816]
As discussed on stand, we need to find a solution for the mobile usability challenges. 

Could be adding a list of links to the mobile view.

**Comment by beccaklam** [comment]
@hannahkane @caltrider 
Waiting to see what options are available when we get the proper thinglink account. Any word on that? @ScottDowne and I are thinking there may be some solutions once we have more agency over the thinglink styling (the free account has just very basic styling).

**Comment by caltrider** [comment]
@beccaklam Talk to @cadecairos about getting access to the Thinklink account. He can get you set-up in it to play around and answer your questions

**Comment by ScottDowne** [comment]
Becca showed me this. It seems to have some acceptable options, and it's all solved within the act of making the thinglink, which is good.

**Comment by ScottDowne** [comment]
@beccaklam There is no action from us, we just need to make sure when a thinglink is made, it's made in the proper mobile friendly way.

I think we can close this because investigation is done, a solution is found, and no dev or design is required. At this point all I see left is making sure every thinglink is made in the proper way, which is probably not something we need to keep as an open ticket. Maybe we want a new ticket on documenting the process for making a thinglink and shipping it to production (once we have a production setup).

**Comment by ScottDowne** [comment]
Feel free to reopen if you think closing this  was too soon. :)
