### ISSUE TITLE
More emoji on typeoutloud.org

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#845]
More emoij somehow! It makes typeoutloud really fun
- maybe we have a hint that tells people how for a particular OS (control+command+space for mac)
- can we trigger keyboard with emoji for android and ios?

**Comment by hannahkane** [comment]
And/Or maybe upvoting is done in the form of choosing an emoji?

**Comment by ScottDowne** [comment]
This one is particularly challenging because the emojis seem to be built into some sort of standards?

Seems to be whatever is searchable in here: http://emojipedia.org/

Is built into the font and the browser, meaning we get all of this for free because of the web.

If we want custom emojjis we need a custom thing to load these.

**Comment by HPaulJohnson** [comment]
closing / won't fix.
