### ISSUE TITLE
SafetyFirst video: Password Manager

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#882]
Content TK

Localization needs TK

Assignee TK

:)

**Comment by brettgaylor** [comment]
Script:
https://docs.google.com/document/d/1ULTvg5dTbnnqLTtCP1E-RB1dKtx8EBhp4E5gwVsnv-w/edit

Roughcut:
https://drive.google.com/open?id=0B0bF99sa1fRJMFlZdDlSQ01QbWs

**Comment by natalieworth** [comment]
@brettgaylor Placed the video in the RR template and updated the type:
https://drive.google.com/a/mozilla.com/file/d/0B20-0lpP23c0WDBZR3pTYnA3eU0/view?usp=sharing
Things I have left to do:
- add the 2 texting skype interface shots at the beginning
- add subtitles (we could also do this in the facebook upload directly in the 'closed-caption' option too?) Instead of having it in the video export itself?
- add intro text card for 2nd interviewee
- add credits/ attributions for images and audio
- fix audio at the end

**Comment by brettgaylor** [comment]
Awesome.  Lookin' profesh.
Final notes:
-----
-Add Georgia's title on the first shot - this should feel seperate from the interface of skype, so just use like a white box with Mozilla style black type

"Georgia Bullen, Technology Projects Director
Open Technology Institute"

-Put Harlo in a similar (but different) Skype-ish frame - maybe just change colours?

-Add her title "Harlo Holmes, Freedom Of The Press Foundation" with the same treatment as Georgia

-change the frame a bit with Georgia in the final shot - maybe just have it be closer on her

-fade out music
