### ISSUE TITLE
Design: Increase % of ppl confirming their email address

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#900]
As discussed on Advocacy call today, let's consider a design solution for increasing the number of people who complete the sign-up process by confirming their email address. 

What can we add to the experience to signal that an email is coming and the user needs to click on it?

We can design something specifically for the NN comment collection page, but maybe we should also think more broadly about how this solution could work across all future sign-up pages. (The NN one feels particularly tricky, since the email signup has some conditional logic on the form.)

**Comment by roseregina** [comment]
fwiw, we get a lot of emails in desk.com that are in response to the confirmation email. most of them fall into one of the following three categories: 
1)" thanks!" (no idea if they clicked through and actually confirmed) 
2) a written indication hat they think they are able to confirm by replying to the email
3) a statement that they will not click links sent via email because it's dangerous

**Comment by hannahkane** [comment]
interesting. this is really useful information. out of curiosity, how do we respond in each of these situations?

**Comment by roseregina** [comment]
we don't

**Comment by beccaklam** [comment]
Hey @vojtechmzl We put in some language (basically, "a confirmation email is coming") in the thank modal of the safety first site: https://advocacy.mozilla.org/en-US/safety that begins to address this issue of users not clicking on the email signup confirmation email. Do you know what the best way of seeing whether or not this improves our email signup would be? CC: @hannahkane

**Comment by hannahkane** [comment]
Also wondering if we know any other information about the problem—do we know whether the emails are getting caught in spam filters, for example?

@stephaniemcv - can you let us know the subject line of the email and who it's from? Is it the same confirmation email regardless of where you sign up from across Mozilla?

**Comment by beccaklam** [comment]
@stephaniemcv would I also be able to get a copy of the confirmation e-mail? Whatever variations there are?

**Comment by beccaklam** [comment]
Some suggestions I found from rifling around the internet:

**To optimize the thank you message:**
 * Show what Name/Email address that the confirm email will come from (best would be something from @mozilla)

 * Show subject line of the email

 * What they have to do (click the confirm link)

 * Brief reminder of what they'll begin to get once they do so

 * You might experiment with throwing in an extra bonus (this could be our physical safety kit in the future!), saying something on the thank you page like "confirm now and you'll also receive __________"

 * Video (or GIF? Image?)  showing them how to click the link 

   Example of how the site I grabbed this from does this:

   http://www.aweber.com/blog/thank-you/

**To optimize the confirmation e-mail:**

- Customize the subject line
- Possible Subject Iterations:
       _"Your Response Needed: Activate Your Simple Web Tutorials"
       "Response Required: Get Your Quickstart Video Tutorials"
       "To Get Your Simple Web 2.0 Videos, Confirm Your Email Address"_
- The confirm email also gives you an opportunity to briefly remind your subscribers what it is they'll be getting when they confirm. Sample text you might use in the message body:

       "Thanks for requesting your free Quickstart Video Tutorials! To start learning how to create Web 2.0 applications, please...

         *** Click The Link Below ***

       As promised, you'll get access to 3 videos, plus a 4th special bonus video that will get you well on your way to developing your own web app".

Sources: https://help.aweber.com/hc/en-us/articles/204028986-How-Can-I-Improve-My-Confirmation-Rate-
https://blog.aweber.com/email-marketing/confirmed-opt-in-get-creative.htm

CC: @hannahkane @HPaulJohnson @stephaniemcv @roseregina Thoughts? We could add some of these optimizations and run some tests. The image/video option looks interesting and the rest of the changes seem simple enough.

**Comment by beccaklam** [comment]
Here's a good resource for how to spice up the confirmation email as well: 
https://emaildesign.beefree.io/2016/01/subscription-confirmation-email-tips/

**Comment by stephaniemcv** [comment]
Landing in SPAM box is always a possibility, but I don't think it's the biggest factor here (I'll do some in-depth digging because I can't definitively rule it out off the top of my head). Double opt-ins typically have a pretty big drop off, hence why a lot of organizations prefer single-opt in.  We get a lot of replyback to the confirms and welcomes in Desk and we are doing more delieverability work right now. 

@hannahkane Confirmations Subject line: "Action required: Final step"
From is: Mozilla <Mozilla@e.mozilla.org> 

It is a similar confirmation if you come from Firefox. The differences are the logo and From name are Firefox, the subject line is "Action required: Confirm your subscription to Firefox"

@beccaklam I'll forward you both confirms.

We recently moved to a unified template for the confirms and MoCo has done some testing around Firefox confirms. Will post as soon as I find that deck.

**Comment by stephaniemcv** [comment]
@beccaklam another great resource is https://litmus.com/blog/, we use their tool for SPAM and rendering tests.

**Comment by beccaklam** [comment]
@hannahkane @stephaniemcv The confirmation emails look pretty good to me. We should probably try optimizing our thank you modals first. We haven't done a lot to let the user know a confirmation email is coming and what to do with it.

**Comment by vojtechsedlak** [comment]
@beccaklam love the idea of testing the user flow on the thank you pages/modals and how we can optimize for increasing double optins, while not hurting other possible actions, such as sharing (not applicable on /safety, but is on other sites where we use share progress). We will be able to glean the impact of the current version once we collect enough data. We can compare the double opt-in rate to our averages from other signup landing pages.

**Comment by stephaniemcv** [comment]
+1 to focusing on testing the thank you modals first. 

Here's the <a href="https://mana.mozilla.org/wiki/display/FIREFOX/Optimize+Newsletter+Confirmation+Email">testing results</a> from Firefox confirms using MoFo content.

**Comment by lovegushwa** [comment]
@beccaklam can you screen shot the confirmation emails and add to this ticket? 

@hannahkane @stephaniemcv 
- How extensively have we tested subject lines? 
- Also wondering if we can incentivize confirming right away, like "confirm now and get a bonus blah blah blah."

**Comment by stephaniemcv** [comment]
@lovegushwa 
Confirms have not been extensively tested and this is because it's a triggered send and requires a manual process of setting version A up, letting it run for set time, then swapping in B and then letting it run for the same set time. Also, the same confirm is used across MoFo, regardless of what list you join, so you have to be careful that content can't get too specific to one program. 

Team Email has no plans to move the confirms off of triggered sends to journeys. While journeys would allow us to do testing and customizing more easily, they don't send as fast as triggers. And we want that confirm to hit the inbox right away.

**Comment by hannahkane** [comment]
Closing as not a priority right now
