### ISSUE TITLE
Safety First iteration: allow users to submit safety tips

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#903]
As suggested by @stephaniemcv and @roseregina on today's team call!

Let's consider what the workflow might look like:
 * What information would we want to collect from the user?
 * Would we use a form? Or just an email address? Something else?
 * Should user-submitted tips be public (perhaps so people can +1), or should we vet them internally and only share them once we have a video or some other polished artifact?
 * What would be our process for reviewing tips as they come in?
 * How could we credit/recognize users for sharing their tips?

Feel free to drop thoughts/ideas in comments below, and we can also discuss on an Advocacy Media call soon.

**Comment by roseregina** [comment]
>Should we use a form? Or just an email address? Something else?

I would be inclined to use a form set up to avoid having this be a place that people are also _asking_ security questions. with email, I think there is more of an expectation that there will be a response if requested, whereas a form is commonly understood as unidirectional. 

>Should user-submitted tips be public (perhaps so people can +1), or should we vet them internally and only share them once we have a video or some other polished artifact?

I think that the only way to handle this responsibly is to vet them first. I have concerns about the media literacy skills of the general population. I don't think that we can count on people understanding that we haven't vetted the tips and instead accepting them as "mozilla approved" preemptively. 

>What would be our process for reviewing tips as they come in?

I would be happy to assist with reviewing tips

>How could we credit/recognize users for sharing their tips?

are we sure we want to? I'm not saying that we should or shouldn't, per se, just that this might be something where we should be able to put forward an explicit logic for doing so that goes beyond "people like getting credit and it's a form of supporter engagement". 
I am particularly curious about any information people have about if crediting ideas either increases or decreases participation by groups perceived as having less authority on the topic (women, black and latino people, people from a lower SES background-- all of which are group belongings that people will make assumptions about related to names and online handles).

**Comment by stephaniemcv** [comment]
What information would we want to collect from the user? - I would say just the text of their safety tip. I'm in agreement with @roseregina, any info on the use, we don't really have a good use case to collect anything else. To say thank you? We can do that on the website. To being part of some sort of safety committee? Maybe, if we've developed some sort of cultivation campaign. 

Would we use a form? Or just an email address? Something else? - My vote would be form. 

 Should user-submitted tips be public (perhaps so people can +1), or should we vet them internally and only share them once we have a video or some other polished artifact? - I think they need vetting for correct info and consolidation, as we'll get duplicate tips.

What would be our process for reviewing tips as they come in? - This might be an opportunity to get trusted community members involved in addition to staff? Or some Fellows/Alumni Fellows?  

How could we credit/recognize users for sharing their tips? - I don't think we'll be able to so on an individual level, but maybe we could tie it back to the Data Privacy Day survey and just call our tipsters our Mr. Robots? Though, I'm not sure that localizes well.

**Comment by brettgaylor** [comment]
One suggested here: we could actually make videos or other works that feature the tip submitter (if they are interested). We could have skype calls or something similar. Could be a neat content format - cc @HPaulJohnson

**Comment by lovegushwa** [comment]
I agree with @brettgaylor, we could also create a banner and swap out the sign up CTA. For now we're including a footer link as per @HPaulJohnson suggestion.

**Comment by HPaulJohnson** [comment]
would be cool but i don't think this is going to happen. closing.
