### ISSUE TITLE
Design Safety Tips ad box

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#906]
Here's how Upworthy has described:

[Here](https://www.upworthy.com/how-is-starbucks-giving-baristas-the-perfect-way-to-avoid-student-debt-free-tuition?c=hpstream) is an example of a live sponsored story. In the right rail, you'll see a branded rectangle that we call the engagement box. It's really just another opportunity to engage our audience with Mozilla and will contain your branding and a quick call to action. What we need in order to implement that is a finished 300x600 and 300x250 creative OR we can create it with the following: 
High res logo (330x220)
URL to direct readers
Any photo assets you'd like to include 
Call to action or campaign copy ex: "Learn more," or "Like us on Facebook"
Thanks!
Alyssa

**Comment by lovegushwa** [comment]
@brettgaylor @HPaulJohnson I checked out Starbucks link above. Would be helpful to know a little more about the article (title, an overview of content). We can probably get away with "Keeping you and your digital loved ones secure" as the campaign copy.

**Comment by brettgaylor** [comment]
@lovegushwa Here are the articles they've pitched us
https://docs.google.com/document/d/1BQU5f4ZzmNiKXGd6zQOjikNnKni6fGc525C4-KG4kSQ/edit#heading=h.tf6ywxt9koox

We are going for numbers #1 and #3. That should give you a sense of where the ads will appear, but I think you should think of the ad as an ad for "safety first".  If the "you and your loved ones" copy is what we are going for, then yes that could be appropriate, or we could be more literal "Mozilla has safety tips to keep you and your loved ones secure"

**Comment by lovegushwa** [comment]
@brettgaylor @HPaulJohnson if these will work for unworthy they are ready to go, otherwise the logo is also in that folder and they can make one, or @natalieworth come up with something.

The final files are here:
https://drive.google.com/drive/folders/0B2qu3ExKWIlvNy1rbFhzMXBHQUU?usp=sharing


<img width="653" alt="screen shot 2017-05-26 at 9 16 53 pm" src="https://cloud.githubusercontent.com/assets/12228435/26517938/d1aa3fac-4258-11e7-9186-503e30ba0041.png">

**Comment by brettgaylor** [comment]
Done!
