### ISSUE TITLE
QA>loading jankiness

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#935]
Feels like there is something with react in that the template loads, and then the content of the template loads afterwords.  Does react have any methods to wait to display until the content is loaded?  I seem to remember angular used to have that when we used with webmaker...

Here's an example of what I mean
https://dl.dropboxusercontent.com/u/7968133/loading.m4v

**Comment by ScottDowne** [comment]
It looks like those are the images loading. We can optimize, smaller images (in bytes), less images, images as a data uri, or placeholder heights in the images. These are things I can do that can all help.

I'm getting giddy to take a look at the hosting. Maybe hosting the images somewhere else helps, server cache, cloudfront (which it's not using  because it's staging and wasn't setup) or prod simple loading this from pros fixes this.

I would be very very surprised if this is anything react related. We do react server side, then just have the server send back the static html. React then just does it's thing client side after the user starts to interact with the page.

Worth filing though. Its def reproducible and not intended.

**Comment by ScottDowne** [comment]
I did some stuff on my end, image compression, placeholder sizes for image while they load, and made some assets not load blocking.

I also got Giddy to get us a proper staging app, instead of the janky heroku one. So going forward, this is a slightly better (faster) staging link, which is going to load as fast as production: https://advocacy.mofostaging.net/en-US/safety

I think the other current glaring issue is the fonts loading is bad, which is what you're currently seeing.
